import { test, expect } from '@playwright/test';
import { fileURLToPath } from 'node:url';
const output = name => fileURLToPath(new URL(`../../../.visual-check/${name}`, import.meta.url));
test('custom dates, readable annual chart and mobile layout', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/ui-tests/analytics-review.html');
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();
  await page.getByRole('button', { name: 'Escolher período personalizado' }).click();
  await page.getByLabel('Data inicial').fill('2024-01-01');
  await page.getByLabel('Data final').fill('2025-01-01');
  await page.getByRole('button', { name: 'Aplicar período' }).click();
  await expect(page.getByRole('alert')).toContainText('até 366 dias');
  await page.getByLabel('Data inicial').fill('2026-01-01');
  await page.getByLabel('Data final').fill('2026-01-07');
  const request = page.waitForFunction(() => document.querySelector('.analytics-range-label')?.textContent.includes('01/01/2026'));
  await page.getByRole('button', { name: 'Aplicar período' }).click(); await request;
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();
  await page.getByRole('button', { name: 'Ano atual' }).click();
  await expect(page.locator('.analytics-chart-dates span')).toHaveCount(5);
  await page.screenshot({ path: output('desktop.png'), fullPage: true, animations: 'disabled' });
  await page.getByText('Ver valores por dia', { exact: true }).click();
  await expect(page.locator('.analytics-daily-details tbody tr')).toHaveCount(250);
  await page.getByText('Ver valores por dia', { exact: true }).click();
  await page.setViewportSize({ width: 375, height: 844 });
  await page.screenshot({ path: output('mobile.png'), fullPage: true, animations: 'disabled' });
  await page.screenshot({ path: output('analytics-mobile-top.png'), animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Escolher período personalizado' }).click();
  await expect(page.getByLabel('Data inicial')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('late responses cannot replace another period or store; errors can retry', async ({ page }) => {
  await page.goto('/ui-tests/analytics-review.html');
  await expect(page.getByText('Produto da loja a')).toBeVisible();
  await page.getByRole('button', { name: 'Ano atual' }).click();
  await page.getByRole('button', { name: 'Trocar loja' }).click();
  await expect(page.getByText('Produto da loja a')).toHaveCount(0);
  await expect(page.getByText('Produto da loja b')).toBeVisible();
  await page.waitForTimeout(1100);
  await expect(page.getByText('Produto da loja a')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Hoje', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Ano atual' }).click();
  await page.getByRole('button', { name: 'Ontem', exact: true }).click();
  await expect(page.locator('.analytics-chart-dates span').last()).toHaveText('07/01');
  await page.waitForTimeout(1100);
  await expect(page.locator('.analytics-chart-dates span').last()).toHaveText('07/01');
  await page.getByRole('button', { name: 'Alternar erro' }).click();
  await page.getByRole('button', { name: 'Atualizar', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('última consulta');
  await page.getByRole('button', { name: 'Alternar erro' }).click();
  await page.getByRole('button', { name: 'Tentar novamente' }).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
});
test('zero sales show an honest empty state and zero sessions stay zero', async ({ page }) => {
  await page.goto('/ui-tests/analytics-review.html');
  await expect(page.locator('.overview-card')).toContainText('0 criados');
  await page.getByRole('button', { name: 'Alternar sem vendas' }).click();
  await page.getByRole('button', { name: 'Atualizar', exact: true }).click();
  await expect(page.locator('.analytics-chart-empty')).toContainText('Nenhuma venda paga');
  await expect(page.locator('.trend-card')).toContainText('Sem vendas');
});
