import { test, expect } from '@playwright/test';
import { fileURLToPath } from 'node:url';
const output = name => fileURLToPath(new URL(`../../../.visual-check/${name}`, import.meta.url));
test('admin creates, edits, filters and publishes a roadmap item to the merchant board', async ({ page }) => {
  await page.goto('/ui-tests/roadmap-review.html');
  await page.getByRole('button', { name: 'Novo item', exact: true }).click();
  const form = page.getByRole('form');
  await form.getByLabel('Título', { exact: true }).fill('Exportação de relatórios');
  await form.getByRole('textbox', { name: 'Descrição', exact: true }).fill('Exportar dados de vendas para uma planilha.');
  await form.getByLabel('Status do item').selectOption('IN_PROGRESS');
  await page.screenshot({ path: output('desktop.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: output('mobile.png'), fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await form.getByRole('button', { name: 'Criar item', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Item criado');
  await page.getByRole('button', { name: 'Visão do lojista' }).click();
  await page.getByRole('tab', { name: 'Roadmap', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Exportação de relatórios' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Administração', exact: true }).click();
  let card = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Exportação de relatórios' }) });
  await card.getByRole('button', { name: 'Editar', exact: true }).click();
  await form.getByLabel('Título', { exact: true }).fill('Relatórios prontos para exportar');
  await form.getByLabel('Status do item').selectOption('DONE');
  await form.getByLabel('Visível para os lojistas').check();
  await form.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.getByRole('status')).toContainText('atualizado');
  await page.getByLabel('Filtrar por status').selectOption('DONE');
  await expect(page.getByRole('article')).toHaveCount(1);
  await page.getByRole('button', { name: 'Visão do lojista' }).click();
  await page.getByRole('tab', { name: 'Roadmap', exact: true }).click();
  await expect(page.locator('.roadmap-column.green')).toContainText('Relatórios prontos para exportar');
  await page.getByRole('button', { name: 'Administração', exact: true }).click();
  card = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Relatórios prontos para exportar' }) });
  await card.getByRole('button', { name: 'Ocultar', exact: true }).click();
  await expect(card).toContainText('Oculto para os lojistas');
});
test('existing platform card is editable; failed saves preserve the draft; deletion persists', async ({ page }) => {
  await page.goto('/ui-tests/roadmap-review.html');
  const card = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Novas integrações de frete' }) });
  await card.getByRole('button', { name: 'Editar', exact: true }).click();
  const form = page.getByRole('form');
  await form.getByRole('textbox', { name: 'Descrição', exact: true }).fill('Integrações revisadas para o próximo ciclo.');
  await page.getByRole('button', { name: 'Alternar falha' }).click();
  await form.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.getByRole('alert')).toContainText('Falha simulada');
  await expect(form.getByRole('textbox', { name: 'Descrição', exact: true })).toHaveValue('Integrações revisadas para o próximo ciclo.');
  await page.getByRole('button', { name: 'Alternar falha' }).click();
  await form.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(card).toContainText('Integrações revisadas');
  await expect(card).toContainText('4 votos');
  await card.getByRole('combobox').selectOption('BACKLOG');
  await expect(page.getByRole('status')).toContainText('Status do roadmap atualizado');
  page.once('dialog', dialog => dialog.accept());
  await card.getByRole('button', { name: 'Excluir', exact: true }).click();
  await expect(card).toHaveCount(0);
  await page.getByRole('button', { name: 'Visão do lojista' }).click();
  await page.getByRole('tab', { name: 'Roadmap', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Novas integrações de frete' })).toHaveCount(0);
});
