import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Download, Filter, MessageCircle, RefreshCw, Search, ShoppingCart } from 'lucide-react';
import { getAbandonedCarts } from './api';
import './abandoned-carts-page.css';

const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const emptyMetrics = { totalCents:0, averageCents:0, pendingCents:0, pendingCount:0, abandonedCount:0 };
const finiteNumber = (value, fallback=0) => { const number=Number(value); return Number.isFinite(number)?number:fallback; };
export function normalizeAbandonedCartsResponse(result={}) {
  const items=(Array.isArray(result?.items)?result.items:[]).map((item,index)=>{
    const source=item&&typeof item==='object'?item:{};
    const lastStage=['IDENTIFICATION','SHIPPING','PAYMENT'].includes(source.lastStage)?source.lastStage:'IDENTIFICATION';
    return {...source,publicId:source.publicId||`legacy-cart-${index}`,customer:source.customer&&typeof source.customer==='object'?source.customer:{},items:Array.isArray(source.items)?source.items:[],lastStage,totalCents:Math.max(0,finiteNumber(source.totalCents)),lastActivityAt:source.lastActivityAt||source.updatedAt||null};
  });
  const total=Math.max(0,finiteNumber(result?.total,items.length));
  const metrics={...emptyMetrics,...(result?.metrics&&typeof result.metrics==='object'?result.metrics:{})};
  metrics.totalCents=Math.max(0,finiteNumber(metrics.totalCents));
  metrics.averageCents=Math.max(0,finiteNumber(metrics.averageCents,total?Math.round(metrics.totalCents/total):0));
  return {...result,items,total,page:Math.max(1,finiteNumber(result?.page,1)),pageSize:Math.max(1,finiteNumber(result?.pageSize,20)),pages:Math.max(1,finiteNumber(result?.pages,1)),metrics};
}
const stages = { IDENTIFICATION:'Dados pessoais', SHIPPING:'Endereço', PAYMENT:'Pagamento' };
function phone(value){ let digits=String(value||'').replace(/\D/g,'').replace(/^0+/,''); if(digits.length===10||digits.length===11)digits=`55${digits}`; return /^\d{12,15}$/.test(digits)?digits:null; }
function whatsapp(cart){ const number=phone(cart.customer?.phone); if(!number)return null; const first=cart.customer?.name?.trim().split(/\s+/)[0]; return `https://wa.me/${number}?text=${encodeURIComponent(`${first?`Olá, ${first}!`:'Olá!'} Vi que você iniciou uma compra em nossa loja e não concluiu. Posso ajudar?`)}`; }
function csvCell(value){ return `"${String(value??'').replaceAll('"','""')}"`; }

export default function AbandonedCartsPage({storeKey}){
  const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(20); const [searchInput,setSearchInput]=useState('');
  const [filters,setFilters]=useState({search:'',stage:'',period:'',sort:'newest'});
  const [state,setState]=useState({loading:true,error:'',items:[],total:0,pages:1,metrics:{totalCents:0,averageCents:0}});
  const load=()=>{ const controller=new AbortController(); setState(current=>({...current,loading:true,error:''})); getAbandonedCarts({page,pageSize,...filters},controller.signal).then(result=>setState({loading:false,error:'',...normalizeAbandonedCartsResponse(result)})).catch(error=>{if(error.name!=='AbortError')setState(current=>({...current,loading:false,error:error.message}));}); return controller; };
  useEffect(()=>{const timer=setTimeout(()=>setFilters(value=>({...value,search:searchInput.trim()})),300);return()=>clearTimeout(timer);},[searchInput]);
  useEffect(()=>{const controller=load();return()=>controller.abort();},[page,pageSize,filters,storeKey]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>setPage(1),[pageSize,filters,storeKey]);
  const update=(key,value)=>setFilters(current=>({...current,[key]:value}));
  const exportCsv=async()=>{ const first=normalizeAbandonedCartsResponse(await getAbandonedCarts({page:1,pageSize:100,...filters})); const items=[...first.items]; for(let current=2;current<=first.pages;current+=1){const result=normalizeAbandonedCartsResponse(await getAbandonedCarts({page:current,pageSize:100,...filters}));items.push(...result.items);} const rows=[['Cliente','E-mail','Etapa','Valor','Última visita'],...items.map(cart=>[cart.customer?.name||'',cart.customer?.email||'',stages[cart.lastStage]||cart.lastStage||'Dados pessoais',money.format(finiteNumber(cart.totalCents)/100),cart.lastActivityAt?new Date(cart.lastActivityAt).toLocaleString('pt-BR'):''])]; const blob=new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const link=document.createElement('a');link.href=url;link.download=`carrinhos-abandonados-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url); };
  const average=useMemo(()=>finiteNumber(state.metrics?.averageCents,state.total?Math.round(finiteNumber(state.metrics?.totalCents)/state.total):0),[state]);
  return <main className="page abandoned-page abandoned-management">
    <section className="page-title abandoned-title"><div><h1>Carrinhos abandonados</h1><p>{state.total.toLocaleString('pt-BR')} carrinhos · Visualize e recupere vendas interrompidas no checkout</p></div><button className="secondary" onClick={exportCsv} disabled={state.loading||!state.total}><Download size={16}/> Exportar CSV</button></section>
    <section className="card abandoned-shell">
      <div className="abandoned-summary"><div><span>Total de carrinhos</span><strong>{state.total.toLocaleString('pt-BR')}</strong></div><div><span>Valor total</span><strong>{money.format(state.metrics.totalCents/100)}</strong></div><div><span>Média por carrinho</span><strong>{money.format(average/100)}</strong></div></div>
      <div className="abandoned-controls"><label className="abandoned-search"><Search size={18}/><input value={searchInput} onChange={event=>setSearchInput(event.target.value)} placeholder="Buscar por nome ou e-mail..." aria-label="Buscar carrinhos"/></label><div className="abandoned-filter-row"><label><Filter size={16}/><span className="sr-only">Etapa</span><select value={filters.stage} onChange={event=>update('stage',event.target.value)}><option value="">Todas as etapas</option><option value="IDENTIFICATION">Dados pessoais</option><option value="SHIPPING">Endereço</option><option value="PAYMENT">Pagamento</option></select></label><label><CalendarDays size={16}/><span className="sr-only">Período</span><select value={filters.period} onChange={event=>update('period',event.target.value)}><option value="">Todo período</option><option value="today">Hoje</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option></select></label><label><span>Ordenar</span><select value={filters.sort} onChange={event=>update('sort',event.target.value)}><option value="newest">Mais recentes</option><option value="oldest">Mais antigos</option><option value="highest">Maior valor</option><option value="lowest">Menor valor</option></select></label><button className="filter-refresh" onClick={load} aria-label="Atualizar carrinhos"><RefreshCw size={16}/></button></div></div>
      {state.loading?<div className="abandoned-state"><RefreshCw className="abandoned-spinner"/><span>Carregando carrinhos...</span></div>:state.error?<div className="abandoned-state error"><b>Não foi possível carregar os carrinhos</b><span>{state.error}</span><button className="secondary" onClick={load}>Tentar novamente</button></div>:!state.items.length?<div className="abandoned-state"><ShoppingCart/><b>Nenhum carrinho encontrado</b><span>Ajuste os filtros ou aguarde novos clientes iniciarem o checkout.</span></div>:<div className="abandoned-table-wrap"><table className="abandoned-table"><thead><tr><th>Cliente</th><th>Etapa</th><th>Valor</th><th>Última visita</th><th>Ações</th></tr></thead><tbody>{state.items.map(cart=>{const wa=whatsapp(cart);const itemCount=cart.items.reduce((sum,item)=>sum+Number(item.quantity||0),0);return <tr key={cart.publicId}><td><strong>{cart.customer?.name||'Cliente não identificado'}</strong><small>{cart.customer?.email||'E-mail não informado'} · {itemCount} {itemCount===1?'item':'itens'}</small></td><td><span className={`stage-badge ${cart.lastStage.toLowerCase()}`}>{stages[cart.lastStage]||cart.lastStage}</span></td><td><strong>{money.format(cart.totalCents/100)}</strong></td><td><time dateTime={cart.lastActivityAt}>{new Date(cart.lastActivityAt).toLocaleString('pt-BR',{dateStyle:'medium',timeStyle:'short'})}</time></td><td>{wa?<a href={wa} target="_blank" rel="noreferrer" className="whatsapp-action" aria-label={`Chamar ${cart.customer?.name||'cliente'} no WhatsApp`}><MessageCircle size={18}/></a>:<span className="no-action" title="Telefone não informado"><MessageCircle size={18}/></span>}</td></tr>;})}</tbody></table></div>}
      {!state.loading&&!state.error&&state.total>0&&<footer className="abandoned-pagination"><div><span>Resultado {`${(page-1)*pageSize+1}–${Math.min(page*pageSize,state.total)}`} de {state.total}</span><select value={pageSize} onChange={event=>setPageSize(Number(event.target.value))}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></div><div><button aria-label="Página anterior" disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft size={17}/></button><span>Página {page} de {state.pages}</span><button aria-label="Próxima página" disabled={page>=state.pages} onClick={()=>setPage(value=>value+1)}><ChevronRight size={17}/></button></div></footer>}
    </section>
  </main>;
}
