import { useEffect, useState } from 'react';
import { getAccessAudit } from './admin-support-api';
import './platform-team.css';

const labels = { 'admin.role.admin_granted': 'Administrador adicionado', 'admin.role.admin_revoked': 'Administrador removido', 'admin.support.started': 'Suporte iniciado', 'admin.support.ended': 'Suporte encerrado', 'admin.support.request': 'Acesso à dashboard', 'admin.support.result': 'Resultado da ação', 'admin.role.created': 'Perfil criado', 'admin.role.updated': 'Perfil atualizado', 'admin.role.deleted': 'Perfil excluído', 'admin.role.assigned': 'Perfil atribuído' };
export default function AccessAuditPage() {
  const [page, setPage] = useState(1), [data, setData] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setError(''); getAccessAudit(page).then(result => active && setData(result)).catch(cause => active && setError(cause.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [page, refresh]);
  return <main className="page"><section className="page-title"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Histórico de acessos</h1><p>Entradas de suporte, ações executadas e alterações de permissões.</p></div><button className="secondary" disabled={loading} onClick={() => setRefresh(value => value + 1)}>Atualizar</button></section>{error && <p className="admin-users-error" role="alert">{error}</p>}<section className="card platform-audit">{loading ? <p role="status">Carregando histórico...</p> : !data?.items.length ? <p>Nenhum acesso registrado ainda.</p> : data.items.map(event => <article key={event.id}><div><b>{labels[event.action] || event.action}</b><time>{new Date(event.createdAt).toLocaleString('pt-BR')}</time></div><p>{event.actor?.name || 'Sistema'} · {event.metadata?.targetName || event.targetId}</p>{event.metadata?.reason && <p>Motivo: {event.metadata.reason}</p>}<small>{event.metadata?.mode === 'MAINTENANCE' ? 'Manutenção' : event.metadata?.mode === 'READ_ONLY' ? 'Consulta' : ''} {event.metadata?.method} {event.metadata?.route} {event.metadata?.statusCode ? `· HTTP ${event.metadata.statusCode}` : ''}</small><details><summary>Detalhes do registro</summary><pre>{JSON.stringify({ requestId: event.requestId, ...event.metadata }, null, 2)}</pre></details></article>)}</section><nav className="platform-pagination" aria-label="Páginas do histórico"><button className="secondary" disabled={loading || page === 1} onClick={() => setPage(value => value - 1)}>Anterior</button><span>Página {page} de {data?.pagination.pages || 1}</span><button className="secondary" disabled={loading || page >= (data?.pagination.pages || 1)} onClick={() => setPage(value => value + 1)}>Próxima</button></nav></main>;
}
