import { defaultCheckoutFooterMethods } from "./CheckoutFooter";
export const defaultBlockOrder = ["hero", "timer", "progress", "content"];
export const defaultCheckoutConfig = {
  template: "minimal",
  layout: "split",
  primary: "#7357e9",
  pageBg: "#f6f7f9",
  cardBg: "#ffffff",
  headerBg: "#ffffff",
  textColor: "#17171a",
  pageTextColor: "#17171a",
  headerTextColor: "#17171a",
  buttonTextColor: "#ffffff",
  borderColor: "#e5e5e9",
  inputBg: "#ffffff",
  radius: 14,
  font: "Plus Jakarta Sans",
  logoText: "SOLID",
  logoUrl: "",
  seoTitle: "",
  seoDescription: "",
  faviconUrl: "",
  heroImageUrl: "",
  heroMobileImageUrl: "",
  heroEnabled: false,
  heroHeight: 220,
  secureHeader: true,
  secureText: "Pagamento 100% seguro",
  showProgress: true,
  progressStyle: "outline",
  progressActiveColor: "#7357e9",
  progressInactiveColor: "#ffffff",
  progressActiveTextColor: "#ffffff",
  timer: true,
  timerText: "Oferta reservada por",
  timerMinutes: 10,
  timerStyle: "bar",
  timerBgColor: "#151c2c",
  timerTextColor: "#ffffff",
  timerNumberColor: "#ff515a",
  timerRadius: 14,
  socialProofEnabled: false,
  socialProofPosition: "bottom-left",
  socialProofVisibleSeconds: 5,
  socialProofIntervalSeconds: 9,
  socialProofHeadline: "{nome} acabou de comprar {produto}.",
  socialProofSecondary: "há {tempo}",
  socialProofPreviewMessages:
    "Mariana | 5 minutos | este item | São Paulo\nGabriel | 8 minutos | este item | Curitiba",
  socialProofIcon: "check",
  socialProofCloseButton: true,
  socialProofBackgroundColor: "#ffffff",
  socialProofTextColor: "#111827",
  socialProofSecondaryColor: "#6b7280",
  socialProofBorderColor: "#e5e7eb",
  socialProofIconBackgroundColor: "#10b981",
  socialProofIconColor: "#ffffff",
  socialProofRadius: 16,
  socialProofShadow: "soft",
  eyebrow: "FINALIZE SEU PEDIDO",
  title: "Você está a um passo.",
  subtitle: "Preencha seus dados para gerar o Pix. Leva menos de um minuto.",
  summaryTitle: "Resumo da compra",
  summaryBannerUrl: "",
  summaryBannerFit: "cover",
  buttonText: "Gerar Pix agora",
  showCoupon: true,
  showBump: true,
  showSummary: true,
  showTrust: true,
  trustBenefit1: "Pagamento protegido",
  trustBenefit2: "Confirmação automática",
  trustBenefit3: "Seus dados estão seguros",
  testimonialName: "Cliente verificado",
  testimonialText: "Compra simples, rápida e segura.",
  testimonials: [
    {
      id: "default",
      name: "Cliente verificado",
      text: "Compra simples, rápida e segura.",
      imageUrl: "",
      rating: 5,
    },
  ],
  customElements: [],
  footerEnabled: true,
  footerBackgroundColor: "#000000",
  footerTextColor: "#ffffff",
  footerAlignment: "center",
  footerLayout: "centered",
  footerPadding: 48,
  footerPaymentMethodsEnabled: true,
  footerPaymentTitle: "Formas de pagamento",
  footerPaymentMethods: defaultCheckoutFooterMethods,
  footerCompanyName: "Solid Commerce",
  footerCompanyDocument: "",
  footerCompanyAddress: "",
  footerSecureBadgeEnabled: true,
  footerSecureText: "Pagamento 100% seguro",
  footerShowPolicies: true,
  footerText: "© 2026 Solid Commerce. Todos os direitos reservados.",
  privacyUrl: "#",
  termsUrl: "#",
  language: "pt-BR",
  currency: "BRL",
  successUrl: "",
  buttonEffect: "lift",
  blockOrder: defaultBlockOrder,
};
Object.assign(defaultCheckoutConfig, {
  contentWidth: 1120,
  elementGlobalStyle: { radius: 12, spacing: 12, fontScale: 100 },
  orderBumpProductId: "",
  orderBumpTitle: "",
  orderBumpMessage: "",
});
Object.assign(defaultCheckoutConfig, {
  buttonBgColor: "#7357e9",
  inputBorderColor: "#e5e5e9",
  inputRadius: 10,
  progressInactiveTextColor: "#777780",
  progressLabelColor: "#777780",
  progressActiveLabelColor: "#17171a",
});
Object.assign(defaultCheckoutConfig, {
  heroDevice: "all",
  timerDevice: "all",
  progressDevice: "all",
  summaryDevice: "desktop",
  summaryBannerDevice: "desktop",
  trustDevice: "all",
});
