import React, { useState } from 'react';
import { ArrowLeft, Check, ChevronDown, ChevronRight, Clock3, Eye, Laptop, LayoutTemplate, Monitor, Palette, Save, Send, ShieldCheck, Smartphone, Tablet, Type, Undo2, Upload, WalletCards } from 'lucide-react';

export const defaultCheckoutConfig={template:'minimal',primary:'#7357e9',pageBg:'#f6f7f9',cardBg:'#ffffff',textColor:'#17171a',borderColor:'#e5e5e9',inputBg:'#ffffff',radius:14,font:'Plus Jakarta Sans',logoText:'SOLID',secureHeader:true,timer:true,timerText:'Oferta reservada por',timerMinutes:10,title:'Você está a um passo.',subtitle:'Preencha seus dados para gerar o Pix. Leva menos de um minuto.',buttonText:'Gerar Pix agora',showCoupon:true,showBump:true,showSummary:true,footerText:'© 2026 Solid Commerce. Todos os direitos reservados.',privacyUrl:'#',termsUrl:'#',language:'pt-BR',currency:'BRL',successUrl:'',buttonEffect:'lift'};
const groups=[['Modelos',LayoutTemplate],['Aparência',Type],['Cores',Palette],['Cabeçalho',Monitor],['Elementos',WalletCards],['Conteúdo das etapas',Type],['Pagamentos',WalletCards],['Rodapé',Type],['Políticas',ShieldCheck],['Efeitos dos botões',Save],['Escassez',Clock3],['Rastreamento de saída',Eye],['Campos personalizados',Type],['Moeda e idioma',WalletCards],['SEO',Monitor]];
Object.assign(defaultCheckoutConfig,{orderBumpProductId:''});
let editorProducts=[];
let createOrderBump=async()=>{};
const Field=({label,children,help})=><label className="editor-field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>;
const Toggle=({checked,onChange,label})=><button type="button" className={`editor-toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)} aria-pressed={checked} aria-label={label}><span/></button>;
const Color=({label,value,onChange})=><Field label={label}><div className="color-field"><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><input value={value.toUpperCase()} onChange={e=>/^#[0-9a-f]{0,6}$/i.test(e.target.value)&&onChange(e.target.value)} maxLength="7"/></div></Field>;

function Settings({group,c,u}){
 const line=(label,key)=><div className="setting-line"><span>{label}</span><Toggle checked={c[key]} onChange={v=>u(key,v)} label={label}/></div>;
 if(group==='Modelos')return <><h3>Escolha um modelo</h3><p className="panel-help">Use uma base e personalize todos os detalhes.</p><div className="template-grid">{[['minimal','Minimal'],['conversion','Conversão'],['compact','Compacto']].map(([id,n])=><button key={id} className={c.template===id?'selected':''} onClick={()=>u('template',id)}><span className={`template-thumb ${id}`}><i/><i/><i/></span><b>{n}</b>{c.template===id&&<Check size={14}/>}</button>)}</div></>;
 if(group==='Aparência')return <><h3>Estrutura do checkout</h3><Field label="Tipografia"><select value={c.font} onChange={e=>u('font',e.target.value)}><option>Plus Jakarta Sans</option><option>Inter</option><option>Arial</option><option>Georgia</option></select></Field><Field label={`Arredondamento — ${c.radius}px`}><input type="range" min="0" max="28" value={c.radius} onChange={e=>u('radius',+e.target.value)}/></Field>{line('Resumo do pedido','showSummary')}</>;
 if(group==='Cores')return <><h3>Cores gerais</h3>{[['Cor principal','primary'],['Fundo da página','pageBg'],['Fundo dos cards','cardBg'],['Texto principal','textColor'],['Bordas','borderColor'],['Fundo dos inputs','inputBg']].map(([l,k])=><Color key={k} label={l} value={c[k]} onChange={v=>u(k,v)}/>)}</>;
 if(group==='Cabeçalho')return <><h3>Cabeçalho</h3><Field label="Nome ou texto da logo"><input value={c.logoText} maxLength="24" onChange={e=>u('logoText',e.target.value)}/></Field><button className="upload-zone"><Upload size={18}/><span><b>Enviar logo</b><small>PNG, JPG ou WebP até 2 MB</small></span></button>{line('Selo de pagamento seguro','secureHeader')}</>;
 if(group==='Elementos')return <><h3>Elementos do checkout</h3>{line('Cupom','showCoupon')}{line('Order bump','showBump')}{c.showBump&&<><Field label="Produto da oferta complementar" help="O item entra no Pix somente se o cliente aceitar."><select value={c.orderBumpProductId||''} onChange={e=>u('orderBumpProductId',e.target.value)}><option value="">Nenhum produto selecionado</option>{editorProducts.map(p=><option key={p.publicId} value={p.publicId}>{p.checkoutTitle} — R$ {(p.priceCents/100).toFixed(2).replace('.',',')}</option>)}</select></Field><details className="order-bump-create"><summary>Criar novo produto de order bump</summary><Field label="Nome do produto"><input value={c.orderBumpDraftTitle||''} maxLength="240" onChange={e=>u('orderBumpDraftTitle',e.target.value)} placeholder="Ex.: Garantia estendida"/></Field><Field label="Preço (R$)"><input inputMode="decimal" value={c.orderBumpDraftPrice||''} onChange={e=>u('orderBumpDraftPrice',e.target.value)} placeholder="29,90"/></Field><Field label="Descrição curta"><textarea rows="2" value={c.orderBumpDraftDescription||''} maxLength="10000" onChange={e=>u('orderBumpDraftDescription',e.target.value)} placeholder="Explique o que o cliente recebe"/></Field><Field label="URL da imagem (opcional)"><input type="url" value={c.orderBumpDraftImageUrl||''} onChange={e=>u('orderBumpDraftImageUrl',e.target.value)} placeholder="https://..."/></Field><button type="button" className="editor-action order-bump-create-button" onClick={()=>void createOrderBump()}>Criar e selecionar produto</button></details></>}{line('Resumo do pedido','showSummary')}</>;
 if(group==='Conteúdo das etapas')return <><h3>Textos da identificação</h3><Field label="Título"><input value={c.title} onChange={e=>u('title',e.target.value)}/></Field><Field label="Texto auxiliar"><textarea rows="3" value={c.subtitle} onChange={e=>u('subtitle',e.target.value)}/></Field><Field label="Texto do botão"><input value={c.buttonText} onChange={e=>u('buttonText',e.target.value)}/></Field></>;
 if(group==='Escassez')return <><h3>Escassez</h3>{line('Ativar cronômetro','timer')}<Field label="Texto"><input value={c.timerText} onChange={e=>u('timerText',e.target.value)}/></Field><Field label="Duração em minutos"><input type="number" min="1" max="60" value={c.timerMinutes} onChange={e=>u('timerMinutes',+e.target.value)}/></Field></>;
 if(group==='Rodapé')return <><h3>Rodapé</h3><Field label="Texto legal"><textarea rows="3" value={c.footerText} onChange={e=>u('footerText',e.target.value)}/></Field></>;
 if(group==='Políticas')return <><h3>Políticas</h3><Field label="URL de privacidade"><input value={c.privacyUrl} onChange={e=>u('privacyUrl',e.target.value)}/></Field><Field label="URL dos termos"><input value={c.termsUrl} onChange={e=>u('termsUrl',e.target.value)}/></Field></>;
 if(group==='Moeda e idioma')return <><h3>Moeda e idioma</h3><Field label="Idioma"><select value={c.language} onChange={e=>u('language',e.target.value)}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English</option><option value="es">Español</option></select></Field><Field label="Moeda"><select value={c.currency} onChange={e=>u('currency',e.target.value)}><option>BRL</option><option>USD</option><option>EUR</option></select></Field></>;
 if(group==='Efeitos dos botões')return <><h3>Efeito do botão</h3><Field label="Interação"><select value={c.buttonEffect} onChange={e=>u('buttonEffect',e.target.value)}><option value="lift">Elevar suavemente</option><option value="pulse">Pulso sutil</option><option value="none">Sem efeito</option></select></Field></>;
 if(group==='Rastreamento de saída')return <><h3>Rastreamento de saída</h3><Field label="URL após aprovação" help="Só redirecionar após confirmação server-side."><input placeholder="https://sualoja.com/obrigado" value={c.successUrl} onChange={e=>u('successUrl',e.target.value)}/></Field></>;
 return <><h3>{group}</h3><div className="panel-empty"><ShieldCheck size={24}/><b>Configuração preparada</b><p>Este bloco será conectado às regras do backend na próxima etapa.</p></div></>;
}

function Preview({c,device}){const s={'--ep':c.primary,'--ebg':c.pageBg,'--ecard':c.cardBg,'--etext':c.textColor,'--eborder':c.borderColor,'--einput':c.inputBg,'--eradius':`${c.radius}px`,fontFamily:c.font};return <div className={`editor-device ${device} template-${c.template}`} style={s}><div className="ep-page"><div className="ep-header"><b>{c.logoText||'SUA MARCA'}</b>{c.secureHeader&&<span><ShieldCheck size={15}/> PAGAMENTO<br/>100% SEGURO</span>}</div><div className="ep-body">{c.timer&&<div className="ep-timer">{c.timerText}: <strong>00 : {String(c.timerMinutes).padStart(2,'0')} : 00</strong></div>}<div className="ep-steps"><span className="active"><i>1</i>Identificação</span><span><i>2</i>Entrega</span><span><i>3</i>Pagamento</span></div>{c.showSummary&&<div className="ep-summary"><b>Resumo do pedido</b><strong>R$ 148,00</strong><ChevronDown size={15}/></div>}<div className="ep-card"><h2>{c.title}</h2><p>{c.subtitle}</p><label>Nome completo<input placeholder="Ex.: Maria da Silva"/></label><label>E-mail<input placeholder="Ex.: maria@email.com"/></label><div className="ep-two"><label>CPF/CNPJ<input placeholder="000.000.000-00"/></label><label>Celular / WhatsApp<input placeholder="(00) 00000-0000"/></label></div>{c.showCoupon&&<button className="ep-coupon">+ Adicionar cupom</button>}</div>{c.showBump&&<div className="ep-bump"><span/><div><b>Oferta especial</b><p>Adicione o Guia de Resultados</p></div><strong>+ R$ 29,90</strong></div>}<button className={`ep-button effect-${c.buttonEffect}`}>{c.buttonText}<ChevronRight size={16}/></button><small className="ep-safe"><ShieldCheck size={13}/> Seus dados estão protegidos.</small></div><div className="ep-footer">{c.footerText}<span><a href={c.privacyUrl}>Privacidade</a> · <a href={c.termsUrl}>Termos</a></span></div></div></div>}

export default function CheckoutEditor({onBack,onPreview,checkout,onSaveDraft,onPublish,onCreateOrderBump,products=[]}){editorProducts=products;
 const load=()=>({...defaultCheckoutConfig,...(checkout?.draftConfig||{})});
 const [c,setC]=useState(load),[saved,setSaved]=useState(load),[history,setHistory]=useState([load()]),[group,setGroup]=useState(null),[device,setDevice]=useState('mobile'),[toast,setToast]=useState(''),[busy,setBusy]=useState(false);const dirty=JSON.stringify(c)!==JSON.stringify(saved);
 const u=(k,v)=>setC(old=>{const next={...old,[k]:v};setHistory(h=>[...h.slice(-19),next]);return next});const undo=()=>setHistory(h=>{if(h.length<2)return h;const n=h.slice(0,-1);setC(n.at(-1));return n});const msg=t=>{setToast(t);setTimeout(()=>setToast(''),1900)};createOrderBump=async()=>{const title=(c.orderBumpDraftTitle||'').trim();const price=Math.round(Number(String(c.orderBumpDraftPrice||'').replace(',','.'))*100);if(!title||!Number.isInteger(price)||price<1){msg('Informe nome e preço válido para o order bump');return}setBusy(true);try{const product=await onCreateOrderBump({title,priceCents:price,description:(c.orderBumpDraftDescription||'').trim(),imageUrl:(c.orderBumpDraftImageUrl||'').trim()});u('orderBumpProductId',product.publicId);u('orderBumpDraftTitle','');u('orderBumpDraftPrice','');u('orderBumpDraftDescription','');u('orderBumpDraftImageUrl','');msg('Produto criado e selecionado no order bump')}catch(error){msg(error.message)}finally{setBusy(false)}};const save=async()=>{setBusy(true);try{await onSaveDraft(c);setSaved(c);msg('Rascunho salvo no servidor')}catch(error){msg(error.message)}finally{setBusy(false)}};const publish=async()=>{setBusy(true);try{if(dirty){await onSaveDraft(c);setSaved(c)}await onPublish();msg('Checkout publicado com sucesso')}catch(error){msg(error.message)}finally{setBusy(false)}};
 return <div className="checkout-editor"><header className="editor-top"><button className="icon-btn" onClick={onBack}><ArrowLeft size={19}/></button><div className="editor-search"><b>Checkout principal</b><span>{dirty?'Alterações não salvas':'Salvo'}</span></div><div className="device-picker">{[['mobile',Smartphone],['tablet',Tablet],['desktop',Laptop]].map(([id,I])=><button key={id} className={device===id?'active':''} onClick={()=>setDevice(id)}><I size={17}/></button>)}</div><div className="editor-actions"><button className="editor-action" onClick={undo} disabled={history.length<2}><Undo2 size={16}/> Desfazer</button><button className="editor-action" onClick={()=>onPreview(c)}><Eye size={16}/> Visualizar</button><button className="editor-action" onClick={save} disabled={!dirty}><Save size={16}/> Salvar rascunho</button><button className="publish-btn" onClick={publish}><Send size={16}/> Publicar</button></div></header><div className="editor-layout"><aside className="editor-panel">{group&&<button className="panel-back" onClick={()=>setGroup(null)}><ArrowLeft size={16}/> Voltar</button>}{!group?<nav>{groups.map(([n,I])=><button key={n} onClick={()=>setGroup(n)}><I size={17}/><span>{n}</span><ChevronRight size={16}/></button>)}</nav>:<div className="panel-settings"><Settings group={group} c={c} u={u}/></div>}</aside><main className="editor-canvas"><Preview c={c} device={device}/></main></div>{toast&&<div className="editor-toast"><Check size={16}/>{toast}</div>}</div>;
}
