import { useEffect, useState } from 'react';
import { CheckCircle2, KeyRound, LoaderCircle, Save, ShieldCheck, WalletCards } from 'lucide-react';
import { getWestPayStatus, saveWestPay } from './api';
import './gateways-page.css';

export default function GatewaysPage({ csrfToken, storeKey }) {
  const [status, setStatus] = useState({ loading: true, connected: false }); const [form, setForm] = useState({ apiKey: '', publicKey: '' }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = () => getWestPayStatus().then(value => setStatus({ ...value, loading: false })).catch(error => { setStatus({ loading: false, connected: false }); setMessage(error.message); });
  useEffect(() => { void load(); }, [storeKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const submit = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { await saveWestPay(form, csrfToken); setForm({ apiKey: '', publicKey: '' }); setMessage('WestPay conectada e validada com sucesso.'); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <main className="page gateways-page"><section className="page-title"><div><p className="eyebrow">CHECKOUT</p><h1>Gateways</h1><p>Conecte o provedor que receberá os pagamentos desta loja.</p></div>{status.connected && <span className="connection-pill connected"><CheckCircle2 size={15}/> Ativo</span>}</section>{message && <div className="integration-alert" role="status">{message}</div>}<section className="gateway-layout"><form className="card gateway-form" onSubmit={submit}><div className="gateway-heading"><span><WalletCards size={25}/></span><div><h2>WestPay</h2><p>Pix real com confirmação automática de pagamento.</p></div></div>{status.loading ? <div className="integration-loading"><LoaderCircle className="spin"/> Verificando...</div> : <><label>API Key<input type="password" autoComplete="new-password" value={form.apiKey} onChange={event => setForm(current => ({ ...current, apiKey: event.target.value }))} placeholder="live_..." required/></label><label>Public Key<input type="password" autoComplete="new-password" value={form.publicKey} onChange={event => setForm(current => ({ ...current, publicKey: event.target.value }))} placeholder="Cole a Public Key da WestPay" required/></label><small className="gateway-note"><KeyRound size={14}/> As chaves são testadas na WestPay e armazenadas com criptografia AES-GCM.</small><button className="primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17}/> : <Save size={17}/>} {status.connected ? 'Atualizar credenciais' : 'Conectar WestPay'}</button></>}</form><aside className="card gateway-security"><ShieldCheck size={25}/><h2>Primeiro: Pix</h2><p>O checkout calcula o total no servidor e envia somente os dados necessários à WestPay.</p><ul><li>Credenciais nunca chegam ao navegador</li><li>Preço e frete recalculados no servidor</li><li>Uma tentativa identificada por sessão</li><li>Cartão será liberado somente com estratégia PCI-DSS</li></ul></aside></section></main>;
}
