import React, { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, LoaderCircle, RefreshCw, Unplug } from 'lucide-react';
import { getIntegrationDiagnostics } from './api';

const labels = { healthy: 'Funcionando', warning: 'Atenção', disconnected: 'Não conectado' };
const eventLabels = { catalog_sync: 'Catálogo sincronizado', webhook: 'Webhook confirmado', waiting_payment: 'Pix criado', paid: 'Venda paga', refunded: 'Reembolso', InitiateCheckout: 'Checkout iniciado', AddPaymentInfo: 'Pagamento iniciado', Purchase: 'Compra confirmada', PENDING: 'Pix aguardando', PAID: 'Pagamento confirmado' };
const date = value => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : 'Nenhum evento registrado';

export default function IntegrationDiagnostics({ storeKey }) {
  const [state, setState] = useState({ loading: true, data: null, error: '' });
  const load = () => { const controller = new AbortController(); setState(current => ({ ...current, loading: true, error: '' })); getIntegrationDiagnostics(controller.signal).then(data => setState({ loading: false, data, error: '' })).catch(error => { if (error.name !== 'AbortError') setState(current => ({ ...current, loading: false, error: error.message })); }); return controller; };
  useEffect(() => { const controller = load(); return () => controller.abort(); }, [storeKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const items = state.data?.integrations || []; const healthy = items.filter(item => item.status === 'healthy').length;
  return <section className="diagnostics card"><header><div><p className="eyebrow">SAÚDE DA OPERAÇÃO</p><h2>Diagnóstico das integrações</h2><p>Status e últimos eventos registrados na loja selecionada.</p></div><div className="diagnostics-summary"><span>{healthy} de {items.length || 5} funcionando</span><button className="secondary" type="button" disabled={state.loading} onClick={load}>{state.loading ? <LoaderCircle className="spin" size={16}/> : <RefreshCw size={16}/>} Atualizar</button></div></header>{state.error && <div className="integration-alert" role="alert">{state.error}</div>}{state.loading && !state.data ? <div className="integration-loading"><LoaderCircle className="spin"/> Verificando integrações...</div> : <div className="diagnostics-grid">{items.map(item => <article key={item.provider} className={`diagnostic-item ${item.status}`}><span className="diagnostic-icon">{item.status === 'healthy' ? <CheckCircle2/> : item.status === 'warning' ? <AlertTriangle/> : <Unplug/>}</span><div><div className="diagnostic-name"><strong>{item.name}</strong><em>{labels[item.status]}</em></div><p>{item.detail || (item.connected ? 'Credencial validada e ativa.' : 'Configure esta integração para começar.')}</p><small>{item.lastEvent ? `${eventLabels[item.lastEvent.event] || item.lastEvent.event || 'Evento'} · ${date(item.lastEvent.at)}` : date(null)}</small></div></article>)}</div>}<footer>Última checagem: {date(state.data?.checkedAt)}</footer></section>;
}
