import React, { useEffect, useState } from 'react';
import { BarChart3, CheckCircle2, KeyRound, LoaderCircle, ShieldCheck, Unplug } from 'lucide-react';
import { disconnectMeta, getMetaStatus, saveMeta } from './api';

export default function MetaIntegration({ csrfToken, storeKey }) {
  const [status, setStatus] = useState({ loading: true, connected: false }); const [pixelId, setPixelId] = useState(''); const [accessToken, setAccessToken] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = () => getMetaStatus().then(value => setStatus({ ...value, loading: false })).catch(error => { setStatus({ loading: false, connected: false }); setMessage(error.message); });
  useEffect(() => { setStatus({ loading: true, connected: false }); setPixelId(''); setAccessToken(''); setMessage(''); void load(); }, [storeKey]);
  const connect = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const value = await saveMeta({ pixelId, accessToken }, csrfToken); setStatus({ ...value, loading: false }); setPixelId(''); setAccessToken(''); setMessage('Meta Pixel e API de Conversões conectados com sucesso.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const disconnect = async () => { if (!window.confirm('Desconectar a Meta desta loja?')) return; setBusy(true); try { await disconnectMeta(csrfToken); setStatus({ loading: false, connected: false }); setMessage('Meta desconectada.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <section className="utmify-section meta-section"><div className="utmify-title"><div><p className="eyebrow">ANÚNCIOS E CONVERSÕES</p><h2>Meta Pixel</h2><p>Rastreie a jornada do checkout no navegador e confirme conversões pelo servidor.</p></div>{status.connected && <span className="connection-pill connected"><CheckCircle2 size={15}/> Ativo</span>}</div>{message && <div className="integration-alert" role="status">{message}</div>}<div className="integration-layout"><div className="card shopify-card"><div className="integration-heading"><span className="utmify-brand meta-brand"><BarChart3 size={25}/></span><div><h2>Pixel + Conversions API</h2><p>Eventos deduplicados por loja, sem expor o token no checkout.</p></div></div>{status.loading ? <div className="integration-loading"><LoaderCircle className="spin"/> Verificando integração...</div> : status.connected ? <div className="connected-panel"><div><span>Status da integração</span><strong>Rastreamento avançado ativado</strong><small>PageView · ViewContent · InitiateCheckout · AddPaymentInfo · Purchase</small></div><button className="secondary danger-outline" disabled={busy} onClick={disconnect}><Unplug size={17}/> Desconectar</button></div> : <form onSubmit={connect}><label htmlFor="meta-pixel">ID do Pixel</label><div className="utmify-token-field"><BarChart3 size={18}/><input id="meta-pixel" inputMode="numeric" value={pixelId} onChange={event => setPixelId(event.target.value.replace(/\D/g, ''))} placeholder="Ex.: 123456789012345" required/></div><label htmlFor="meta-token">Token da API de Conversões</label><div className="utmify-token-field"><KeyRound size={18}/><input id="meta-token" type="password" value={accessToken} onChange={event => setAccessToken(event.target.value)} placeholder="Cole o token gerado no Gerenciador de Eventos" autoComplete="off" required/></div><button className="primary connect-button" disabled={busy || pixelId.length < 5 || accessToken.trim().length < 20}>{busy ? <LoaderCircle className="spin" size={17}/> : <BarChart3 size={17}/>} {busy ? 'Validando...' : 'Conectar Meta'}</button></form>}</div><aside className="card integration-security"><span><ShieldCheck size={23}/></span><h2>Mensuração protegida</h2><p>O Pixel mede a navegação; o servidor confirma a conversão mesmo com limitações do navegador.</p><ul><li>Deduplicação por event_id</li><li>Dados pessoais enviados com hash SHA-256</li><li>Token criptografado por loja</li><li>Falhas não interrompem a compra</li></ul></aside></div></section>;
}
