import React, { useEffect, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, CreditCard, ExternalLink, MapPin, MessageCircle, Package, RefreshCw, ShoppingBag, UserRound } from 'lucide-react';
import { getOrder, getOrders } from './api';
import './orders-page.css';

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const relative = new Intl.RelativeTimeFormat('pt-BR', { numeric: 'auto' });
const statusLabels = { PAID: 'Pago', PENDING: 'Aguardando Pix', FAILED: 'Falhou', CANCELLED: 'Cancelado', EXPIRED: 'Expirado', REFUNDED: 'Reembolsado' };
const statusTones = { PAID: 'paid', PENDING: 'pending', FAILED: 'failed', CANCELLED: 'neutral', EXPIRED: 'neutral', REFUNDED: 'refunded' };
const orderCode = publicId => `#SLD-${publicId.slice(-6).toUpperCase()}`;
const initials = name => (name || 'Cliente').split(' ').filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase();
const whatsappNumber = phone => { let digits = String(phone || '').replace(/\D/g, '').replace(/^0+/, ''); if (digits.length === 10 || digits.length === 11) digits = `55${digits}`; return /^\d{12,15}$/.test(digits) ? digits : null; };
const whatsappUrl = order => { const number = whatsappNumber(order.customer?.phone); if (!number) return null; const firstName = order.customer?.name?.trim().split(/\s+/)[0]; const product = order.items?.[0]?.titleSnapshot || 'seu produto'; const extra = order.items?.length > 1 ? ' e os outros itens da sua compra' : ''; const greeting = firstName ? `Olá, ${firstName}! Tudo bem?` : 'Olá! Tudo bem?'; const message = `${greeting} Estou entrando em contato sobre sua compra de ${product}${extra} em nossa loja.`; return `https://wa.me/${number}?text=${encodeURIComponent(message)}`; };

function relativeDate(value) { const seconds = Math.round((new Date(value).getTime() - Date.now()) / 1000); if (Math.abs(seconds) < 60) return relative.format(seconds, 'second'); const minutes = Math.round(seconds / 60); if (Math.abs(minutes) < 60) return relative.format(minutes, 'minute'); const hours = Math.round(minutes / 60); return Math.abs(hours) < 24 ? relative.format(hours, 'hour') : relative.format(Math.round(hours / 24), 'day'); }
function PaymentStatus({ status }) { return <span className={`payment-status ${statusTones[status] || 'neutral'}`}><i/>{statusLabels[status] || status}</span>; }

export function OrdersTable({ items, loading, error, onRetry, onOpen }) {
  if (loading) return <div className="orders-state" role="status"><RefreshCw className="orders-spinner"/><span>Carregando pedidos...</span></div>;
  if (error) return <div className="orders-state error" role="alert"><ShoppingBag/><b>Não foi possível carregar os pedidos</b><span>{error}</span><button className="secondary" onClick={onRetry}><RefreshCw size={16}/> Tentar novamente</button></div>;
  if (!items.length) return <div className="orders-state"><ShoppingBag/><b>Nenhum pedido ainda</b><span>Quando um cliente gerar um Pix, o pedido aparecerá aqui automaticamente.</span></div>;
  return <div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Produto</th><th>Valor</th><th>Pagamento</th><th>Criado</th>{onOpen && <th><span className="sr-only">Ações</span></th>}</tr></thead><tbody>{items.map(order => { const product = order.items[0]; const extra = order.items.length > 1 ? ` +${order.items.length - 1}` : ''; const whatsapp = whatsappUrl(order); return <tr key={order.publicId}><td><strong>{orderCode(order.publicId)}</strong><small>{order.paymentProvider || 'WestPay'}</small></td><td><div className="order-customer"><span>{initials(order.customer?.name)}</span><div><strong>{order.customer?.name || 'Cliente não identificado'}</strong><small>{order.customer?.email || 'E-mail indisponível'}</small>{whatsapp && <a className="whatsapp-link compact" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label={`Chamar ${order.customer?.name || 'cliente'} no WhatsApp`}><MessageCircle size={13}/> WhatsApp</a>}</div></div></td><td><div className="order-product"><span>{product?.imageUrlSnapshot ? <img src={product.imageUrlSnapshot} alt="" loading="lazy"/> : <Package size={18}/>}</span><div><strong>{product?.titleSnapshot || 'Produto'}</strong><small>{product?.quantity || 1} un.{extra}</small></div></div></td><td><strong>{currency.format(order.totalCents / 100)}</strong>{order.shippingPriceCents > 0 && <small>inclui frete</small>}</td><td><PaymentStatus status={order.status}/></td><td><time dateTime={order.createdAt} title={new Date(order.createdAt).toLocaleString('pt-BR')}>{relativeDate(order.createdAt)}</time></td>{onOpen && <td><button className="order-open" onClick={() => onOpen(order.publicId)} aria-label={`Abrir detalhes do pedido ${orderCode(order.publicId)}`}>Detalhes <ExternalLink size={14}/></button></td>}</tr>; })}</tbody></table></div>;
}

function useOrders(storeKey, page, pageSize) {
  const [state, setState] = useState({ loading: true, error: '', items: [], total: 0, pages: 1 });
  const load = () => { setState(current => ({ ...current, loading: true, error: '' })); getOrders({ page, pageSize }).then(result => setState({ loading: false, error: '', items: result.items, total: result.total, pages: result.pages })).catch(error => setState({ loading: false, error: error.message, items: [], total: 0, pages: 1 })); };
  useEffect(() => { load(); }, [page, pageSize, storeKey]); // eslint-disable-line react-hooks/exhaustive-deps
  return [state, load];
}

function useOrderDetail(orderId) {
  const [state, setState] = useState({ loading: true, error: '', order: null });
  useEffect(() => { const controller = new AbortController(); setState({ loading: true, error: '', order: null }); getOrder(orderId, controller.signal).then(order => setState({ loading: false, error: '', order })).catch(error => { if (error.name !== 'AbortError') setState({ loading: false, error: error.message, order: null }); }); return () => controller.abort(); }, [orderId]);
  return state;
}

export function RecentOrders({ storeKey, onViewAll }) { const [state, load] = useOrders(storeKey, 1, 5); return <section className="card orders-card"><div className="card-head"><div><h2>Pedidos recentes</h2><p>Últimas movimentações reais do checkout</p></div><button className="ghost" onClick={onViewAll}>Ver todos</button></div><OrdersTable {...state} onRetry={load}/></section>; }

function Address({ address }) { if (!address?.street) return <span>Endereço não informado</span>; return <span>{address.street}, {address.number}{address.complement ? ` — ${address.complement}` : ''}<br/>{address.neighborhood && `${address.neighborhood} — `}{address.city}/{address.state}<br/>{address.postalCode && `CEP ${address.postalCode}`}</span>; }

function OrderDetail({ orderId, onBack }) {
  const { loading, error, order } = useOrderDetail(orderId);
  return <main className="page orders-page"><button className="back-link" onClick={onBack}><ArrowLeft size={17}/> Voltar para pedidos</button>{loading && <section className="card orders-state" role="status"><RefreshCw className="orders-spinner"/><span>Carregando detalhes do pedido...</span></section>}{error && <section className="card orders-state error" role="alert"><ShoppingBag/><b>Não foi possível abrir este pedido</b><span>{error}</span><button className="secondary" onClick={onBack}>Voltar para pedidos</button></section>}{order && <><section className="page-title order-detail-title"><div><p className="eyebrow">PEDIDO</p><h1>{orderCode(order.publicId)}</h1><p>Criado em {new Date(order.createdAt).toLocaleString('pt-BR')}</p></div><PaymentStatus status={order.status}/></section><section className="order-detail-grid"><div className="order-detail-main"><section className="card detail-card"><div className="detail-card-head"><div><Package size={19}/><h2>Itens do pedido</h2></div><strong>{currency.format(order.subtotalCents / 100)}</strong></div>{order.items.map((item, index) => <article className="detail-item" key={`${item.titleSnapshot}-${index}`}><span className="detail-product-image">{item.imageUrlSnapshot ? <img src={item.imageUrlSnapshot} alt=""/> : <Package size={19}/>}</span><div><b>{item.titleSnapshot}</b>{item.variantSnapshot && <small>{item.variantSnapshot}</small>}<small>{item.quantity} {item.quantity === 1 ? 'unidade' : 'unidades'}</small></div></article>)}</section><section className="card detail-card"><div className="detail-card-head"><div><UserRound size={19}/><h2>Cliente</h2></div></div><div className="detail-info"><b>{order.customer?.name || 'Cliente não identificado'}</b><span>{order.customer?.email || 'E-mail não informado'}</span>{order.customer?.phone && <span>{order.customer.phone}</span>}{whatsappUrl(order) && <a className="whatsapp-link" href={whatsappUrl(order)} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/> Chamar no WhatsApp</a>}</div></section><section className="card detail-card"><div className="detail-card-head"><div><MapPin size={19}/><h2>Entrega</h2></div></div><div className="detail-info"><b>{order.shippingMethodName || 'Frete não informado'}</b><Address address={order.shippingAddress}/></div></section></div><aside className="card payment-detail"><div className="payment-detail-icon"><CreditCard size={22}/></div><p className="eyebrow">PAGAMENTO</p><h2>{order.paymentProvider || 'Pix'}</h2><PaymentStatus status={order.status}/><dl><div><dt>Subtotal</dt><dd>{currency.format(order.subtotalCents / 100)}</dd></div><div><dt>Frete</dt><dd>{order.shippingPriceCents === 0 ? 'Grátis' : currency.format(order.shippingPriceCents / 100)}</dd></div><div className="payment-total"><dt>Total</dt><dd>{currency.format(order.totalCents / 100)}</dd></div></dl>{order.paidAt && <p className="payment-confirmed">Confirmado em {new Date(order.paidAt).toLocaleString('pt-BR')}</p>}</aside></section></>}</main>;
}

export default function OrdersPage({ storeKey }) {
  const [page, setPage] = useState(1); const [selectedOrder, setSelectedOrder] = useState(null); const [state, load] = useOrders(storeKey, page, 20);
  useEffect(() => { setSelectedOrder(null); setPage(1); }, [storeKey]);
  if (selectedOrder) return <OrderDetail orderId={selectedOrder} onBack={() => setSelectedOrder(null)}/>;
  return <main className="page orders-page"><section className="page-title"><div><p className="eyebrow">GESTÃO</p><h1>Pedidos</h1><p>Acompanhe pagamentos Pix e vendas da loja selecionada.</p></div></section><section className="card orders-list"><div className="orders-list-head"><div><b>{state.total} {state.total === 1 ? 'pedido' : 'pedidos'}</b><span>Os status são confirmados diretamente pela WestPay.</span></div><button className="secondary" onClick={load} disabled={state.loading}><RefreshCw size={16}/> Atualizar</button></div><OrdersTable {...state} onRetry={load} onOpen={setSelectedOrder}/>{!state.loading && !state.error && state.total > 0 && <div className="orders-pagination"><span>Página {page} de {state.pages}</span><div><button aria-label="Página anterior" disabled={page <= 1} onClick={() => setPage(value => value - 1)}><ChevronLeft size={17}/></button><button aria-label="Próxima página" disabled={page >= state.pages} onClick={() => setPage(value => value + 1)}><ChevronRight size={17}/></button></div></div>}</section></main>;
}
