import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, ImageOff, LoaderCircle, PackagePlus, Plus, Search, Sparkles } from 'lucide-react';
import { getCheckouts, getProducts, publishCheckout, updateCheckoutDraft } from './api';
import { defaultCheckoutConfig } from './CheckoutEditor';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });

export default function OrderBumpsPage({ csrfToken }) {
  const [state, setState] = useState({ loading: true, checkouts: [], products: [], error: '' }); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [editor, setEditor] = useState(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  async function load() { try { const [checkouts, products] = await Promise.all([getCheckouts(), getProducts({ status: 'active', pageSize: 100 })]); setState({ loading: false, checkouts: checkouts.items, products: products.items, error: '' }); } catch (e) { setState(current => ({ ...current, loading: false, error: e.message })); } }
  useEffect(() => { void load(); }, []);
  const checkout = state.checkouts.find(item => item.slug === 'principal') || state.checkouts[0]; const items = useMemo(() => state.checkouts.map(c => ({ checkout: c, product: state.products.find(p => p.publicId === c.draftConfig?.orderBumpProductId) })).filter(item => item.product).filter(item => `${item.product.checkoutTitle} ${item.checkout.name}`.toLowerCase().includes(query.toLowerCase())).filter(item => filter === 'all' || (filter === 'active' ? item.checkout.status === 'PUBLISHED' : item.checkout.status !== 'PUBLISHED')), [state, query, filter]);
  function open(item) { const cfg = item?.checkout?.draftConfig || {}; setEditor({ productId: item?.product?.publicId || '', title: cfg.orderBumpTitle || '', message: cfg.orderBumpMessage || '' }); setNotice(''); }
  async function save() { if (!checkout || !editor.productId) { setNotice('Selecione um produto para a oferta.'); return; } setBusy(true); try { const config = { ...defaultCheckoutConfig, ...(checkout.draftConfig || {}), showBump: true, orderBumpProductId: editor.productId, orderBumpTitle: editor.title.trim(), orderBumpMessage: editor.message.trim() }; await updateCheckoutDraft(checkout.publicId, config, csrfToken); await publishCheckout(checkout.publicId, csrfToken); setEditor(null); await load(); } catch (e) { setNotice(e.message); } finally { setBusy(false); } }
  const selected = state.products.find(p => p.publicId === editor?.productId);
  if (state.loading) return <main className="page"><section className="card products-state"><LoaderCircle className="spin"/><span>Carregando order bumps...</span></section></main>;
  if (editor) return <main className="order-bump-builder"><header><button className="icon-btn" onClick={() => setEditor(null)} aria-label="Voltar"><ArrowLeft size={19}/></button><b>{selected ? 'Editar order bump' : 'Criar order bump'}</b><div><button className="secondary" onClick={() => setEditor(null)}>Cancelar</button><button className="primary" disabled={busy} onClick={() => void save()}>{busy ? <LoaderCircle className="spin" size={16}/> : <Check size={16}/>} Salvar order bump</button></div></header><div className="ob-builder-grid"><section className="ob-form"><div className="ob-tabs"><button className="active">Oferta</button><button type="button" disabled>Aparência</button></div><div className="ob-form-body"><h2>Informações do order bump</h2><label className="ob-toggle">Order bump ativo<input type="checkbox" checked readOnly/><span/></label><label>Título da oferta<input value={editor.title} maxLength="120" onChange={e => setEditor(current => ({ ...current, title: e.target.value }))} placeholder="Ex.: Você ganhou uma oferta especial!"/></label><label>Mensagem complementar<textarea value={editor.message} maxLength="300" onChange={e => setEditor(current => ({ ...current, message: e.target.value }))} placeholder="Ex.: Adicione ao pedido antes de finalizar."/></label><hr/><label>Produto e preço<select value={editor.productId} onChange={e => setEditor(current => ({ ...current, productId: e.target.value }))}><option value="">Selecione um produto...</option>{state.products.map(p => <option key={p.publicId} value={p.publicId}>{p.checkoutTitle} — {money.format(p.priceCents / 100)}</option>)}</select></label><small className="ob-help">Para outro valor, crie o produto com o preço desejado na aba Produtos ou no editor do checkout.</small>{notice && <p className="public-error" role="alert">{notice}</p>}</div></section><section className="ob-preview"><span className="eyebrow">PRÉVIA NO CHECKOUT</span><div className="ob-preview-card"><span className="ob-preview-check"><Check size={14}/></span>{selected?.imageUrl ? <img src={selected.imageUrl} alt=""/> : <span className="ob-preview-image"><Sparkles size={20}/></span>}<div><b>{editor.title || 'Oferta especial'}</b><strong>{selected?.checkoutTitle || 'Selecione um produto'}</strong><p>{editor.message || selected?.checkoutDescription || 'Uma oferta complementar para seu pedido.'}</p></div><em>+ {selected ? money.format(selected.priceCents / 100) : 'R$ 0,00'}</em></div><small>O cliente pode aceitar ou recusar a oferta antes de pagar.</small></section></div></main>;
  return <main className="page order-bumps-page"><section className="page-title"><div><p className="eyebrow">GESTÃO</p><h1>Order bumps</h1><p>Ofertas complementares para aumentar seu ticket médio.</p></div><button className="primary" onClick={() => open()}><Plus size={17}/> Novo order bump</button></section><section className="card ob-list-card"><div className="ob-toolbar"><div className="product-search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por código ou nome..."/></div><div className="ob-filter">{[['all','Todos'],['active','Ativos'],['inactive','Inativos']].map(([value,label]) => <button className={filter === value ? 'active' : ''} key={value} onClick={() => setFilter(value)}>{label}</button>)}</div></div>{state.error && <p className="public-error" role="alert">{state.error}</p>}{items.length ? <div className="order-bump-list">{items.map(item => <button className="order-bump-card" key={item.checkout.publicId} onClick={() => open(item)}><div className="order-bump-thumb">{item.product.imageUrl ? <img src={item.product.imageUrl} alt=""/> : <ImageOff size={21}/>}</div><div><span className="eyebrow">{item.checkout.status === 'PUBLISHED' ? 'ATIVO' : 'RASCUNHO'}</span><h2>{item.checkout.draftConfig?.orderBumpTitle || item.product.checkoutTitle}</h2><p>{item.checkout.draftConfig?.orderBumpMessage || item.product.checkoutDescription || 'Oferta complementar'}</p></div><strong>{money.format(item.product.priceCents / 100)}</strong></button>)}</div> : <div className="ob-empty"><span><PackagePlus size={25}/></span><h2>Nenhum order bump cadastrado</h2><p>Crie seu primeiro order bump para aumentar suas vendas com ofertas adicionais.</p><button className="primary" onClick={() => open()}><Plus size={16}/> Criar order bump</button></div>}</section></main>;
}
