import { useCallback, useEffect, useState } from 'react';
import { Plus, ShieldCheck, Users } from 'lucide-react';
import { getAdminUsers } from './api';
import { assignPlatformRole, deletePlatformRole, getPlatformRoles, getPlatformTeam, savePlatformRole } from './admin-support-api';
import { permissionLabels } from './platform-access';
import './platform-team.css';
import PlatformAdminDialog from './PlatformAdminDialog';

const blankRole = () => ({ name: '', description: '', permissions: [] });
const dependencies = { 'users.manage': 'users.read', 'billing.manage': 'users.read', 'support.read': 'users.read', 'support.write': 'support.read', 'operations.manage': 'operations.read' };
export default function PlatformTeamPage({ csrfToken, operator }) {
  const [adminTarget, setAdminTarget] = useState(null);
  const [roles, setRoles] = useState([]), [members, setMembers] = useState([]), [editing, setEditing] = useState(null);
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [query, setQuery] = useState(''), [results, setResults] = useState([]), [searching, setSearching] = useState(false);
  const load = useCallback(async () => { const [profiles, team] = await Promise.all([getPlatformRoles(), getPlatformTeam()]); setRoles(profiles.roles); setMembers(team.members); }, []);
  useEffect(() => { let active = true; load().catch(cause => active && setError(cause.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [load]);
  const mutate = async (work, message) => { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); setNotice(message); return true; } catch (cause) { setError(cause.message); return false; } finally { setBusy(false); } };
  const changePermission = (permission, checked) => setEditing(current => {
    const values = new Set(current.permissions);
    const add = value => { values.add(value); if (dependencies[value]) add(dependencies[value]); };
    if (checked) add(permission); else { values.delete(permission); for (let i = 0; i < 3; i++) for (const [key, dependency] of Object.entries(dependencies)) if (!values.has(dependency)) values.delete(key); }
    return { ...current, permissions: [...values] };
  });
  const search = async event => { event.preventDefault(); setSearching(true); setError(''); try { const data = await getAdminUsers('APPROVED', 1, query); setResults(data.users.filter(user => !user.platformAdmin && !user.disabledAt && user.publicId !== operator?.publicId)); } catch (cause) { setError(cause.message); } finally { setSearching(false); } };
  const assign = async (user, roleId) => { if (!await mutate(() => assignPlatformRole(user.publicId, roleId || null, csrfToken), `Perfil de ${user.name} atualizado.`)) return; setResults([]); };
  return <main className="page platform-team-page">
    <section className="page-title"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Equipe e permissões</h1><p>Gerencie administradores da plataforma e os perfis da equipe técnica e de compliance.</p></div><button className="primary" onClick={() => setEditing(blankRole())}><Plus size={17}/> Novo perfil</button></section>
    {error && <p className="admin-users-error" role="alert">{error}</p>}{notice && <p className="platform-notice" role="status">{notice}</p>}
    {loading ? <p role="status">Carregando equipe...</p> : <>
      <section className="platform-role-grid" aria-label="Perfis de acesso">{roles.map(role => <article className="card platform-role-card" key={role.publicId}><ShieldCheck size={22}/><h2>{role.name}</h2><p>{role.description || 'Perfil personalizado da plataforma.'}</p><small>{role._count.users} membros · {role.permissions.length} permissões</small><div><button className="secondary" disabled={busy} onClick={() => setEditing({ ...role })}>Editar perfil</button><button className="secondary" disabled={busy || role._count.users > 0} title={role._count.users ? 'Remova os membros antes de excluir' : undefined} onClick={() => { if (window.confirm(`Excluir o perfil ${role.name}?`)) void mutate(() => deletePlatformRole(role.publicId, csrfToken), 'Perfil excluído.'); }}>Excluir</button></div></article>)}</section>
      {editing && <section className="card platform-role-editor"><form onSubmit={async event => { event.preventDefault(); if (await mutate(() => savePlatformRole(editing.publicId, { name: editing.name, description: editing.description, permissions: editing.permissions }, csrfToken), editing.publicId ? 'Perfil salvo. Acessos de suporte anteriores deste perfil foram encerrados.' : 'Perfil criado. Agora você pode atribuir membros.')) setEditing(null); }}><h2>{editing.publicId ? 'Editar perfil' : 'Novo perfil'}</h2><label>Nome do perfil<input required minLength={3} maxLength={80} value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })}/></label><label>Descrição<textarea maxLength={240} value={editing.description} onChange={event => setEditing({ ...editing, description: event.target.value })}/></label><fieldset className="platform-permissions"><legend>Permissões</legend>{Object.entries(permissionLabels).map(([key, label]) => <label key={key}><input type="checkbox" checked={editing.permissions.includes(key)} onChange={event => changePermission(key, event.target.checked)}/><span>{label}</span></label>)}</fieldset><p>A criação de perfis e a atribuição de equipe permanecem exclusivas do administrador principal.</p><footer><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancelar</button><button className="primary" disabled={busy}>Salvar perfil</button></footer></form></section>}
      <section className="card platform-members"><h2><Users size={20}/> Membros da equipe</h2><p>Administradores gerenciam toda a plataforma. Os demais membros seguem as permissões do perfil atribuído.</p>{members.map(member => <article key={member.publicId}><div><b>{member.name}</b><small>{member.email}</small></div>{member.platformAdmin ? <div className="platform-member-actions"><span className="badge">Administrador da plataforma{member.publicId === operator?.publicId ? " · você" : ""}</span>{member.publicId !== operator?.publicId && <button className="secondary" disabled={busy} onClick={() => setAdminTarget(member)}>Remover administrador</button>}</div> : <div className="platform-member-actions"><button className="secondary" disabled={busy || Boolean(member.disabledAt)} onClick={() => setAdminTarget(member)}>Tornar administrador</button><select aria-label={`Perfil de ${member.name}`} value={member.platformRole?.publicId || ''} disabled={busy} onChange={event => void assign(member, event.target.value)}><option value="">Remover da equipe</option>{roles.map(role => <option key={role.publicId} value={role.publicId}>{role.name}</option>)}</select></div>}</article>)}</section>
      <section className="card platform-members"><h2>Adicionar à equipe</h2><p>Busque uma conta ativa já cadastrada para torná-la administradora ou atribuir um perfil de equipe.</p><form className="platform-search" onSubmit={search}><input aria-label="Buscar conta por nome ou e-mail" placeholder="Nome ou e-mail" required minLength={3} maxLength={120} value={query} onChange={event => setQuery(event.target.value)}/><button className="secondary" disabled={searching}>{searching ? 'Buscando...' : 'Buscar conta'}</button></form>{results.map(user => <article key={user.publicId}><div><b>{user.name}</b><small>{user.email}</small></div><div className="platform-member-actions"><button className="secondary" disabled={busy} onClick={() => setAdminTarget(user)}>Tornar administrador</button><select aria-label={`Atribuir perfil a ${user.name}`} value="" disabled={busy} onChange={event => void assign(user, event.target.value)}><option value="" disabled>Escolha um perfil</option>{roles.map(role => <option key={role.publicId} value={role.publicId}>{role.name}</option>)}</select></div></article>)}</section>
    </>}
    {adminTarget && <PlatformAdminDialog user={adminTarget} csrfToken={csrfToken} onClose={() => setAdminTarget(null)} onSaved={enabled => { setAdminTarget(null); setResults([]); setNotice(enabled ? 'Administrador adicionado. A pessoa deve entrar novamente.' : 'Acesso administrativo removido e sessões encerradas.'); void load().catch(cause => setError(cause.message)); }}/>}
  </main>;
}
