import React, { useEffect, useState } from 'react';
import { AlertCircle, ChevronLeft, ChevronRight, ImageOff, LoaderCircle, Package, RefreshCw, Search, ShoppingBag } from 'lucide-react';
import { getProducts } from './api';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const formatMoney = cents => money.format(cents / 100);

export default function ProductsPage({ storeKey, onOpenIntegrations }) {
  const [filters, setFilters] = useState({ search: '', status: '', source: '', page: 1 });
  const [data, setData] = useState({ items: [], total: 0, pages: 1 });
  const [state, setState] = useState('loading'); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); const delay = setTimeout(() => { setState('loading'); setError(''); getProducts(filters, controller.signal).then(result => { setData(result); setState('ready'); }).catch(reason => { if (reason.name !== 'AbortError') { setError(reason.message); setState('error'); } }); }, filters.search ? 300 : 0); return () => { clearTimeout(delay); controller.abort(); }; }, [filters, storeKey]);
  const update = values => setFilters(current => ({ ...current, ...values, page: values.page ?? 1 }));
  const reset = () => setFilters({ search: '', status: '', source: '', page: 1 });

  return <main className="page products-page"><section className="page-title"><div><p className="eyebrow">CATÁLOGO</p><h1>Produtos</h1><p>Produtos importados e disponíveis para seus checkouts.</p></div><button className="secondary" onClick={onOpenIntegrations}><RefreshCw size={16}/> Sincronizar Shopify</button></section>
    <section className="card products-card"><div className="product-toolbar"><label className="product-search"><Search size={17}/><span className="sr-only">Buscar produtos</span><input value={filters.search} onChange={event => update({ search: event.target.value })} placeholder="Buscar por produto, fornecedor ou identificador..."/></label><select aria-label="Filtrar por status" value={filters.status} onChange={event => update({ status: event.target.value })}><option value="">Todos os status</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><select aria-label="Filtrar por origem" value={filters.source} onChange={event => update({ source: event.target.value })}><option value="">Todas as origens</option><option value="shopify">Shopify</option><option value="manual">Manual</option></select></div>
      {state === 'loading' ? <div className="products-state"><LoaderCircle className="spin"/><b>Carregando produtos...</b><span>Buscando o catálogo da loja ativa.</span></div> : state === 'error' ? <div className="products-state error"><AlertCircle/><b>Não foi possível carregar os produtos</b><span>{error}</span><button className="secondary" onClick={() => setFilters(current => ({ ...current }))}>Tentar novamente</button></div> : data.items.length === 0 ? <div className="products-state"><Package/><b>Nenhum produto encontrado</b><span>{filters.search || filters.status || filters.source ? 'Altere os filtros para ampliar a busca.' : 'Sincronize sua Shopify para importar o catálogo.'}</span>{filters.search || filters.status || filters.source ? <button className="secondary" onClick={reset}>Limpar filtros</button> : <button className="primary" onClick={onOpenIntegrations}>Conectar ou sincronizar Shopify</button>}</div> : <><div className="products-summary"><span><strong>{data.total}</strong> {data.total === 1 ? 'produto encontrado' : 'produtos encontrados'}</span></div><div className="products-table-wrap"><table className="products-table"><thead><tr><th>Produto</th><th>Origem</th><th>Preço</th><th>Estoque</th><th>Catálogo</th><th>Status</th></tr></thead><tbody>{data.items.map(product => <tr key={product.publicId}><td><div className="product-cell"><div className="catalog-image">{product.imageUrl ? <img src={product.imageUrl} alt="" loading="lazy"/> : <ImageOff size={20}/>}</div><div><strong>{product.checkoutTitle}</strong><span>{product.vendor || product.productType || product.handle || 'Sem fornecedor informado'}</span></div></div></td><td><span className={`source-chip ${product.source.toLowerCase()}`}>{product.source === 'SHOPIFY' ? <ShoppingBag size={13}/> : <Package size={13}/>} {product.source === 'SHOPIFY' ? 'Shopify' : 'Manual'}</span></td><td><strong>{formatMoney(product.priceCents)}</strong>{product.compareAtCents && <del>{formatMoney(product.compareAtCents)}</del>}</td><td><span>{product.trackInventory ? (product.stockQuantity ?? 0) : 'Não rastreado'}</span></td><td><span className="catalog-counts">{product._count.variants} var. · {product._count.images} img. · {product._count.collections} col.</span></td><td><span className={`status-chip ${product.active ? 'active' : 'inactive'}`}><i/>{product.active ? 'Ativo' : 'Inativo'}</span></td></tr>)}</tbody></table></div><footer className="products-pagination"><span>Página {filters.page} de {data.pages}</span><div><button aria-label="Página anterior" disabled={filters.page <= 1} onClick={() => update({ page: filters.page - 1 })}><ChevronLeft size={17}/></button><button aria-label="Próxima página" disabled={filters.page >= data.pages} onClick={() => update({ page: filters.page + 1 })}><ChevronRight size={17}/></button></div></footer></>}
    </section></main>;
}
