import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Clock3, CreditCard, LoaderCircle, MapPin, ShieldCheck, ShoppingBag, UserRound } from 'lucide-react';
import { createPublicCheckoutSession, getPublicCheckout, getPublicCheckoutSession } from './api';
import './public-session.css';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const publicConfig = value => ({ primary: '#7357e9', pageBg: '#f6f7f9', cardBg: '#ffffff', textColor: '#17171a', borderColor: '#e5e5e9', inputBg: '#ffffff', radius: 14, font: 'Plus Jakarta Sans', logoText: 'SOLID', secureHeader: true, timer: true, timerText: 'Sessão reservada por', title: 'Você está a um passo.', subtitle: 'Preencha seus dados para continuar. Leva menos de um minuto.', buttonText: 'Continuar para entrega', showSummary: true, footerText: '© 2026 Solid Commerce. Todos os direitos reservados.', privacyUrl: '#', termsUrl: '#', buttonEffect: 'lift', ...(value || {}) });
const configStyle = config => ({ '--public-primary': config.primary, '--public-bg': config.pageBg, '--public-card': config.cardBg, '--public-text': config.textColor, '--public-border': config.borderColor, '--public-input': config.inputBg, '--public-radius': `${config.radius}px`, fontFamily: config.font });
const safeQuantity = (value, maximum) => Math.max(1, Math.min(maximum, Number(value) || 1));

function ProductImage({ src, title }) {
  return src ? <img src={src} alt={`Imagem de ${title}`} loading="lazy" /> : <div className="public-product-placeholder" aria-hidden="true"><ShoppingBag /></div>;
}

export default function PublicCheckout({ storeSlug, checkoutSlug }) {
  const [state, setState] = useState({ loading: true, checkout: null, error: '' });
  const [variantId, setVariantId] = useState(''); const [quantity, setQuantity] = useState(1); const [session, setSession] = useState(null); const [busy, setBusy] = useState(false);
  useEffect(() => { const controller = new AbortController(); getPublicCheckout(storeSlug, checkoutSlug, controller.signal).then(({ checkout }) => { setState({ loading: false, checkout, error: '' }); setVariantId(checkout.product.variants?.[0]?.publicId || ''); }).catch(error => { if (error.name !== 'AbortError') setState({ loading: false, checkout: null, error: error.message }); }); return () => controller.abort(); }, [storeSlug, checkoutSlug]);
  const product = state.checkout?.product; const config = publicConfig(state.checkout?.publishedConfig); const variant = product?.variants?.find(item => item.publicId === variantId); const unitPrice = variant?.priceCents ?? product?.priceCents ?? 0; const total = useMemo(() => unitPrice * quantity, [unitPrice, quantity]);
  async function begin() { setBusy(true); setState(current => ({ ...current, error: '' })); try { const result = await createPublicCheckoutSession(storeSlug, checkoutSlug, { quantity, ...(variantId ? { variantId } : {}) }); sessionStorage.setItem(`solid-checkout-session:${result.session.publicId}`, result.token); setSession(result.session); } catch (error) { setState(current => ({ ...current, error: error.message })); } finally { setBusy(false); } }
  if (state.loading) return <div className="public-checkout-state"><LoaderCircle className="spin" /><span>Preparando checkout seguro...</span></div>;
  if (!product) return <div className="public-checkout-state error"><ShoppingBag /><b>Checkout indisponível</b><span>{state.error || 'Confira o endereço e tente novamente.'}</span></div>;
  return <main className="public-checkout" style={configStyle(config)}><header><b>{config.logoText}</b>{config.secureHeader && <span><ShieldCheck size={18} /> Pagamento seguro</span>}</header><div className="public-checkout-grid"><section><p className="eyebrow">FINALIZE SEU PEDIDO</p><h1>{session ? 'Pedido iniciado com segurança.' : 'Revise sua compra'}</h1>{session ? <div className="public-session-created"><Check size={28} /><h2>Sessão criada</h2><p>Os valores foram validados pelo servidor e reservados por 30 minutos.</p><strong>{money.format(session.totalCents / 100)}</strong></div> : <div className="public-form-card">{product.variants?.length > 0 && <label>Variação<select value={variantId} onChange={event => setVariantId(event.target.value)}>{product.variants.map(item => <option key={item.publicId} value={item.publicId}>{item.title} — {money.format(item.priceCents / 100)}</option>)}</select></label>}<label>Quantidade<input type="number" min="1" max={product.maxPerOrder} value={quantity} onChange={event => setQuantity(safeQuantity(event.target.value, product.maxPerOrder))} /></label>{state.error && <p className="public-error" role="alert">{state.error}</p>}<button onClick={begin} disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <ShieldCheck size={18} />} Continuar para pagamento</button></div>}</section><aside><ProductImage src={product.imageUrl} title={product.checkoutTitle} /><h2>{product.checkoutTitle}</h2>{product.checkoutDescription && <p>{product.checkoutDescription}</p>}<div><span>{quantity} × {money.format(unitPrice / 100)}</span><strong>{money.format(total / 100)}</strong></div></aside></div></main>;
}

function useExpiry(expiresAt) {
  const calculate = () => Math.max(0, Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000)); const [remaining, setRemaining] = useState(calculate);
  useEffect(() => { const interval = window.setInterval(() => setRemaining(calculate()), 1000); return () => window.clearInterval(interval); }, [expiresAt]);
  return { remaining, label: `${String(Math.floor(remaining / 60)).padStart(2, '0')}:${String(remaining % 60).padStart(2, '0')}` };
}

function SessionContent({ session }) {
  const expiry = useExpiry(session.expiresAt); const [form, setForm] = useState({ name: '', email: '', document: '', phone: '' }); const [step, setStep] = useState(1);
  const items = session.items?.length ? session.items : [{ quantity: session.quantity, unitPriceCents: session.unitPriceCents, totalCents: session.totalCents, titleSnapshot: session.checkout.product.checkoutTitle, variantSnapshot: session.variant?.title, imageUrlSnapshot: session.variant?.imageUrl || session.checkout.product.imageUrl }];
  const itemCount = items.reduce((sum, item) => sum + item.quantity, 0); const config = publicConfig(session.checkout?.publishedConfig); const update = (field, value) => setForm(current => ({ ...current, [field]: value }));
  const valid = form.name.trim().length >= 3 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email) && form.document.replace(/\D/g, '').length >= 11 && form.phone.replace(/\D/g, '').length >= 10;
  const advance = event => { event.preventDefault(); if (valid && expiry.remaining) setStep(2); };
  return <main className="public-checkout session-checkout" style={configStyle(config)}>
    <header><b>{config.logoText}</b>{config.secureHeader && <span><ShieldCheck size={18} /> Pagamento seguro</span>}</header>
    {config.timer && <div className="session-expiry" role="status"><Clock3 size={17} /><span>{expiry.remaining ? <>{config.timerText} <strong>{expiry.label}</strong></> : <strong>Sessão expirada</strong>}</span></div>}
    <nav className="checkout-progress" aria-label="Etapas do checkout"><span className="active"><i><UserRound size={15} /></i>Identificação</span><b /><span className={step >= 2 ? 'active' : ''}><i><MapPin size={15} /></i>Entrega</span><b /><span><i><CreditCard size={15} /></i>Pagamento</span></nav>
    <div className={`public-checkout-grid ${config.showSummary ? '' : 'without-summary'}`}>
      <section className="customer-step">{step === 1 ? <form onSubmit={advance} noValidate><p className="eyebrow">FINALIZE SEU PEDIDO</p><h1>{config.title}</h1><p className="customer-subtitle">{config.subtitle}</p><div className="customer-form-card"><div className="customer-section-title"><span><UserRound size={19} /></span><div><h2>Seus dados</h2><p>Usaremos essas informações apenas para processar seu pedido.</p></div></div><label>Nome completo<input autoComplete="name" value={form.name} onChange={event => update('name', event.target.value)} placeholder="Como aparece no documento" /></label><div className="customer-field-grid"><label>E-mail<input type="email" autoComplete="email" value={form.email} onChange={event => update('email', event.target.value)} placeholder="voce@email.com" /></label><label>Celular / WhatsApp<input inputMode="tel" autoComplete="tel" value={form.phone} onChange={event => update('phone', event.target.value)} placeholder="(11) 99999-9999" /></label></div><label>CPF ou CNPJ<input inputMode="numeric" value={form.document} onChange={event => update('document', event.target.value)} placeholder="000.000.000-00" /></label></div><button className={`customer-continue effect-${config.buttonEffect}`} type="submit" disabled={!valid || !expiry.remaining}>{config.buttonText} <ArrowRight size={19} /></button><p className="customer-privacy"><ShieldCheck size={14} /> Seus dados estão protegidos e não serão compartilhados.</p></form> : <div className="next-step-placeholder"><span><MapPin size={25} /></span><p className="eyebrow">PRÓXIMA ETAPA</p><h1>Informe o endereço de entrega</h1><p>A identificação foi validada. A persistência segura do cliente e o cálculo de frete serão conectados na próxima implementação.</p><button type="button" onClick={() => setStep(1)}>Voltar e editar dados</button></div>}</section>
      {config.showSummary && <aside className="session-order-summary"><div className="session-summary-title"><div><span>Seu pedido</span><h2>Resumo da compra</h2></div><small>{itemCount} {itemCount === 1 ? 'item' : 'itens'}</small></div><div className="session-items">{items.map(item => <article className="public-line-item" key={`${item.titleSnapshot}-${item.variantSnapshot || 'default'}`}><ProductImage src={item.imageUrlSnapshot} title={item.titleSnapshot} /><div className="line-item-copy"><b>{item.titleSnapshot}</b>{item.variantSnapshot && item.variantSnapshot !== 'Default Title' && <span>{item.variantSnapshot}</span>}<small>Quantidade: {item.quantity}</small><small>{money.format(item.unitPriceCents / 100)} por unidade</small></div><strong>{money.format(item.totalCents / 100)}</strong></article>)}</div><div className="session-totals"><div><span>Subtotal</span><b>{money.format(session.totalCents / 100)}</b></div><div><span>Frete</span><small>Calculado na próxima etapa</small></div><div className="session-grand-total"><span>Total</span><strong>{money.format(session.totalCents / 100)}</strong></div></div><p className="session-security"><ShieldCheck size={16} /> Preços e estoque protegidos contra alterações no navegador.</p></aside>}
    </div>
    <footer className="public-checkout-footer"><span>{config.footerText}</span><div>{config.privacyUrl && <a href={config.privacyUrl}>Privacidade</a>}{config.termsUrl && <a href={config.termsUrl}>Termos de uso</a>}</div></footer>
  </main>;
}

export function PublicSessionCheckout({ sessionId, token }) {
  const [state, setState] = useState({ loading: true, session: null, error: '' });
  useEffect(() => { const controller = new AbortController(); getPublicCheckoutSession(sessionId, token, controller.signal).then(({ session }) => setState({ loading: false, session, error: '' })).catch(error => { if (error.name !== 'AbortError') setState({ loading: false, session: null, error: error.message }); }); return () => controller.abort(); }, [sessionId, token]);
  if (state.loading) return <div className="public-checkout-state"><LoaderCircle className="spin" /><span>Validando carrinho...</span></div>;
  if (!state.session) return <div className="public-checkout-state error"><ShoppingBag /><b>Sessão indisponível</b><span>{state.error}</span></div>;
  return <SessionContent session={state.session} />;
}
