import React, { useEffect, useState } from 'react';
import { Bell, Building2, CheckCircle2, Globe2, LoaderCircle, Save, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import { getSettings, saveSettings } from './api';
import AccountSettings from './AccountSettings';
import DomainsPage from './DomainsPage';

const tabs=[['store','Dados da loja',Building2],['responsible','Dados do responsável',UserRound],['domains','Domínios',Globe2],['users','Usuários',UsersRound],['security','Segurança',ShieldCheck],['notifications','Notificações',Bell]];
const notificationDefaults={salesEnabled:true,newOrder:true,paymentConfirmed:true,includeStoreName:false,productEnabled:true,releases:true,feedback:true};
const roleLabel={OWNER:'Proprietário',ADMIN:'Administrador',ANALYST:'Analista',SUPPORT:'Suporte'};
function Field({label,children,wide=false}){return <label className={`settings-hub-field${wide?' wide':''}`}><span>{label}</span>{children}</label>}
function Switch({checked,onChange,label,hint}){return <label className="settings-switch-row"><span><b>{label}</b><small>{hint}</small></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i aria-hidden="true"/></label>}

export default function SettingsHub({csrfToken}){
 const [tab,setTab]=useState('store'),[data,setData]=useState(null),[loading,setLoading]=useState(true); const [store,setStore]=useState({}),[user,setUser]=useState({}),[preferences,setPreferences]=useState(notificationDefaults); const [status,setStatus]=useState({busy:false,error:'',notice:''});
 const load=async()=>{setLoading(true);try{const result=await getSettings();setData(result);setStore({name:result.store?.name||'',...(result.store?.profile||{})});setUser({name:result.user?.name||'',email:result.user?.email||'',...(result.user?.profile||{})});setPreferences({...notificationDefaults,...(result.preferences||{})});}catch(error){setStatus({busy:false,error:error.message,notice:''})}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const save=async(section,values)=>{setStatus({busy:true,error:'',notice:''});try{const result=await saveSettings(section,values,csrfToken);setStatus({busy:false,error:'',notice:result.activation?.completed?'Cadastro concluído. Sua loja está ativa.':'Alterações salvas com segurança.'});window.dispatchEvent(new CustomEvent('solid:onboarding-updated',{detail:result.activation}));await load()}catch(error){setStatus({busy:false,error:error.message,notice:''})}};
 if(loading&&!data)return <main className="page settings-hub"><div className="settings-hub-loading"><LoaderCircle className="spin"/> Carregando configurações...</div></main>;
 return <main className="page settings-hub"><section className="page-title"><div><p className="eyebrow">CONTA E OPERAÇÃO</p><h1>Configurações</h1><p>Gerencie os dados, acessos e preferências da sua operação.</p></div></section>
 <nav className="settings-hub-tabs" aria-label="Seções das configurações">{tabs.map(([id,label,Icon])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setStatus({busy:false,error:'',notice:''})}}><Icon size={16}/>{label}</button>)}</nav>
 {status.error&&<p className="settings-hub-message error" role="alert">{status.error}</p>}{status.notice&&<p className="settings-hub-message success"><CheckCircle2 size={16}/>{status.notice}</p>}
 <section className="settings-hub-panel">
 {tab==='store'&&<><header><h2>Informações da loja</h2><p>Nome exibido no painel e dados comerciais da operação.</p></header><div className="settings-form-grid"><Field label="Nome da loja"><input value={store.name||''} onChange={e=>setStore({...store,name:e.target.value})}/></Field><Field label="Razão social / nome fiscal"><input value={store.legalName||''} onChange={e=>setStore({...store,legalName:e.target.value})}/></Field><Field label="CPF/CNPJ"><input value={store.document||''} onChange={e=>setStore({...store,document:e.target.value})}/></Field><Field label="Modelo de negócio"><select value={store.businessModel||''} onChange={e=>setStore({...store,businessModel:e.target.value})}><option value="">Selecione</option><option>E-commerce</option><option>Infoproduto</option><option>Serviços</option><option>Assinaturas</option><option>Outro</option></select></Field><Field label="Faturamento mensal"><select value={store.monthlyRevenue||''} onChange={e=>setStore({...store,monthlyRevenue:e.target.value})}><option value="">Selecione</option><option>Até R$ 10 mil</option><option>R$ 10 mil a R$ 50 mil</option><option>R$ 50 mil a R$ 100 mil</option><option>Acima de R$ 100 mil</option></select></Field><Field label="Site"><input value={store.website||''} disabled={Boolean(store.noWebsite)} placeholder="https://sualoja.com" onChange={e=>setStore({...store,website:e.target.value})}/></Field><Field label="Instagram"><input value={store.instagram||''} placeholder="@sualoja" onChange={e=>setStore({...store,instagram:e.target.value})}/></Field><div className="wide"><Switch label="Não possuo site" hint="Marque se sua loja ainda não tem endereço online." checked={Boolean(store.noWebsite)} onChange={v=>setStore({...store,noWebsite:v,website:v?'':store.website})}/></div></div><footer><button className="primary" disabled={status.busy} onClick={()=>void save('store',store)}>{status.busy?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>}Salvar alterações</button></footer></>}
 {tab==='responsible'&&<><header><h2>Identificação do responsável</h2><p>E-mail é fixo por segurança; os demais dados podem ser atualizados.</p></header><div className="settings-form-grid"><Field label="Nome completo"><input value={user.name||''} onChange={e=>setUser({...user,name:e.target.value})}/></Field><Field label="E-mail"><input value={user.email||''} disabled/></Field><Field label="CPF/CNPJ"><input value={user.document||''} onChange={e=>setUser({...user,document:e.target.value})}/></Field><Field label="Data de nascimento"><input type="date" value={user.birthDate||''} onChange={e=>setUser({...user,birthDate:e.target.value})}/></Field><Field label="CEP"><input value={user.zipCode||''} onChange={e=>setUser({...user,zipCode:e.target.value})}/></Field><Field label="Endereço" wide><input value={user.address||''} onChange={e=>setUser({...user,address:e.target.value})}/></Field><Field label="Número"><input value={user.number||''} onChange={e=>setUser({...user,number:e.target.value})}/></Field><Field label="Complemento"><input value={user.complement||''} onChange={e=>setUser({...user,complement:e.target.value})}/></Field><Field label="Bairro"><input value={user.district||''} onChange={e=>setUser({...user,district:e.target.value})}/></Field><Field label="Cidade"><input value={user.city||''} onChange={e=>setUser({...user,city:e.target.value})}/></Field><Field label="Estado (UF)"><input maxLength={2} value={user.state||''} onChange={e=>setUser({...user,state:e.target.value.toUpperCase()})}/></Field></div><footer><button className="primary" disabled={status.busy} onClick={()=>void save('user',user)}><Save size={17}/>Salvar alterações</button></footer></>}
 {tab==='domains'&&<DomainsPage csrfToken={csrfToken}/>} {tab==='security'&&<AccountSettings csrfToken={csrfToken}/>} 
 {tab==='users'&&<><header><h2>Usuários da loja</h2><p>Visualize quem possui acesso e a função atribuída.</p></header><div className="settings-members">{(data?.members||[]).map(member=><article key={member.publicId}><span>{member.name?.slice(0,2).toUpperCase()}</span><div><b>{member.name}{member.publicId===data?.user?.publicId?' · você':''}</b><small>{member.email}</small></div><div><b>{roleLabel[member.role]||member.role}</b><small>{member.role==='OWNER'?'Acesso total à loja':'Acesso conforme a função'}</small></div><em className={member.status==='ACTIVE'?'active':''}>{member.status==='ACTIVE'?'Ativo':'Desativado'}</em></article>)}</div></>}
 {tab==='notifications'&&<><header><h2>Preferências de notificações</h2><p>Escolha quais eventos devem gerar alertas para esta conta.</p></header><div className="settings-notification-groups"><section><h3>Vendas</h3><Switch label="Notificações ativas" hint="Pausa todos os alertas de venda." checked={preferences.salesEnabled} onChange={v=>setPreferences({...preferences,salesEnabled:v})}/><Switch label="Novo pedido" hint="Aviso quando um pedido é criado." checked={preferences.newOrder} onChange={v=>setPreferences({...preferences,newOrder:v})}/><Switch label="Pagamento confirmado" hint="Aviso quando o pagamento é aprovado." checked={preferences.paymentConfirmed} onChange={v=>setPreferences({...preferences,paymentConfirmed:v})}/><Switch label="Nome da loja na mensagem" hint="Inclui o nome da loja no alerta." checked={preferences.includeStoreName} onChange={v=>setPreferences({...preferences,includeStoreName:v})}/></section><section><h3>Novidades e roadmap</h3><Switch label="Notificações ativas" hint="Pausa alertas de produto e roadmap." checked={preferences.productEnabled} onChange={v=>setPreferences({...preferences,productEnabled:v})}/><Switch label="Novas atualizações" hint="Novidades, melhorias, correções e segurança." checked={preferences.releases} onChange={v=>setPreferences({...preferences,releases:v})}/><Switch label="Minhas sugestões e bugs" hint="Mudanças de status nos seus envios." checked={preferences.feedback} onChange={v=>setPreferences({...preferences,feedback:v})}/></section></div><footer><button className="primary" disabled={status.busy} onClick={()=>void save('notifications',preferences)}><Save size={17}/>Salvar preferências</button></footer></>}
 </section></main>;
}
