import React, { useEffect, useState } from 'react';
import { CheckCircle2, ExternalLink, LoaderCircle, Plug, ShieldCheck, ShoppingBag, Unplug } from 'lucide-react';
import { connectShopify, disconnectShopify, getShopifyStatus } from './api';

export default function ShopifyIntegration({ csrfToken, storeKey }) {
  const [status,setStatus]=useState({loading:true,configured:true,connected:false}); const [shop,setShop]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const load=()=>{setStatus(current=>({...current,loading:true}));getShopifyStatus().then(result=>setStatus({...result,loading:false})).catch(error=>{setStatus(current=>({...current,loading:false}));setMessage(error.message)})};
  useEffect(load,[storeKey]);
  useEffect(()=>{const result=new URLSearchParams(window.location.hash.split('?')[1]||'').get('shopify');if(result==='connected')setMessage('Shopify conectada com sucesso.');else if(result)setMessage('Não foi possível concluir a conexão. Tente novamente.');if(result)window.history.replaceState({},'', '/#/integrations')},[]);
  const connect=async event=>{event.preventDefault();setBusy(true);setMessage('');try{const result=await connectShopify(shop,csrfToken);window.location.assign(result.authorizationUrl)}catch(error){setMessage(error.message);setBusy(false)}};
  const disconnect=async()=>{if(!window.confirm('Desconectar a Shopify desta loja? A sincronização será interrompida.'))return;setBusy(true);setMessage('');try{await disconnectShopify(csrfToken);load();setMessage('Integração desconectada.')}catch(error){setMessage(error.message)}finally{setBusy(false)}};
  return <main className="page integrations-page"><section className="page-title"><div><p className="eyebrow">INTEGRAÇÕES</p><h1>Shopify</h1><p>Conecte o catálogo da loja ativa com autorização segura.</p></div><span className={`connection-pill ${status.connected?'connected':''}`}>{status.connected?<CheckCircle2 size={15}/>:<Plug size={15}/>} {status.connected?'Conectado':'Não conectado'}</span></section>
    {message&&<div className="integration-alert" role="status">{message}</div>}<section className="integration-layout"><div className="card shopify-card"><div className="integration-heading"><span className="shopify-brand"><ShoppingBag size={25}/></span><div><h2>Shopify Admin</h2><p>Produtos e variantes serão importados para esta loja SOLID.</p></div></div>
      {status.loading?<div className="integration-loading"><LoaderCircle className="spin"/> Verificando conexão...</div>:status.connected?<div className="connected-panel"><div><span>Loja conectada</span><strong>{status.shopDomain}</strong><small>Permissões: {status.scopes}</small></div><button className="secondary danger-outline" disabled={busy} onClick={disconnect}>{busy?<LoaderCircle className="spin" size={17}/>:<Unplug size={17}/>} Desconectar</button></div>:<form onSubmit={connect}><label htmlFor="shopify-shop">Domínio MyShopify</label><div className="shop-domain-field"><input id="shopify-shop" value={shop} onChange={event=>setShop(event.target.value)} placeholder="minha-loja" autoComplete="off" required/><span>.myshopify.com</span></div><small>Use o domínio original da Shopify, sem https:// ou www.</small><button className="primary connect-button" disabled={busy||!status.configured}>{busy?<LoaderCircle className="spin" size={17}/>:<ExternalLink size={17}/>} {busy?'Redirecionando...':'Conectar com Shopify'}</button>{!status.configured&&<p className="configuration-warning">A integração precisa ser configurada no servidor antes da conexão.</p>}</form>}
    </div><aside className="card integration-security"><span><ShieldCheck size={23}/></span><h2>Conexão protegida</h2><p>Você autoriza o acesso diretamente na Shopify. A SOLID nunca solicita sua senha.</p><ul><li>Acesso mínimo: leitura de produtos</li><li>Token criptografado no banco</li><li>Conexão separada por loja</li><li>Revogação disponível a qualquer momento</li></ul></aside></section></main>;
}
