import React, { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ExternalLink, Images, Layers3, LoaderCircle, Plug, RefreshCw, ShieldCheck, ShoppingBag, Unplug } from 'lucide-react';
import { connectShopify, disconnectShopify, getShopifyStatus, syncShopifyCatalog } from './api';
import ShopifyOnboarding from './ShopifyOnboarding';
import UtmifyIntegration from './UtmifyIntegration';
import MetaIntegration from './MetaIntegration';

const formatDate = value => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : 'Ainda não sincronizado';
const shopHandle = domain => domain?.replace(/\.myshopify\.com$/i, '') ?? '';

export default function ShopifyIntegration({ csrfToken, storeKey }) {
  const [status, setStatus] = useState({ loading: true, configured: true, connected: false, reconnectRequired: false });
  const [shop, setShop] = useState(''); const [busy, setBusy] = useState(false); const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState(''); const [result, setResult] = useState(null);
  const load = () => { setStatus(current => ({ ...current, loading: true })); getShopifyStatus().then(value => { setStatus({ ...value, loading: false }); if (value.shopDomain) setShop(shopHandle(value.shopDomain)); }).catch(error => { setStatus(current => ({ ...current, loading: false })); setMessage(error.message); }); };
  useEffect(() => { void load(); }, [storeKey]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const value = new URLSearchParams(window.location.hash.split('?')[1] || '').get('shopify'); if (value === 'connected') setMessage('Shopify conectada com sucesso. Agora sincronize o catálogo.'); else if (value === 'already_connected') setMessage('Esta loja Shopify já está ativa em outra loja SOLID. Desconecte-a da loja anterior antes de transferir.'); else if (value) setMessage('Não foi possível concluir a conexão. Tente novamente.'); if (value) window.history.replaceState({}, '', '/#/integrations'); }, []);
  const connect = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const value = await connectShopify(shop, csrfToken); window.location.assign(value.authorizationUrl); } catch (error) { setMessage(error.message); setBusy(false); } };
  const disconnect = async () => { if (!window.confirm('Desconectar a Shopify desta loja? A sincronização será interrompida.')) return; setBusy(true); setMessage(''); try { await disconnectShopify(csrfToken); load(); setResult(null); setMessage('Integração desconectada.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const synchronize = async () => { setSyncing(true); setMessage(''); setResult(null); try { const value = await syncShopifyCatalog(csrfToken); setResult(value); setStatus(current => ({ ...current, lastSyncedAt: value.syncedAt })); setMessage('Catálogo sincronizado com sucesso.'); } catch (error) { setMessage(error.message); load(); } finally { setSyncing(false); } };
  const badge = status.reconnectRequired ? <><AlertTriangle size={15}/> Reconexão necessária</> : status.connected ? <><CheckCircle2 size={15}/> Conectado</> : <><Plug size={15}/> Não conectado</>;

  return <main className="page integrations-page"><section className="page-title"><div><p className="eyebrow">INTEGRAÇÕES</p><h1>Shopify</h1><p>Importe o catálogo completo da loja ativa com autorização segura.</p></div><span className={`connection-pill ${status.connected ? 'connected' : ''} ${status.reconnectRequired ? 'reconnect' : ''}`}>{badge}</span></section>
    {status.reconnectRequired && <div className="integration-alert reconnect-alert" role="alert"><AlertTriangle size={18}/><div><strong>Reconecte sua loja Shopify</strong><span>A autorização expirou ou foi revogada. Seus produtos e personalizações continuam salvos, mas novas sincronizações estão pausadas.</span></div></div>}
    {message && <div className="integration-alert" role="status" aria-live="polite">{message}</div>}
    <ShopifyOnboarding key={storeKey} connected={status.connected} synced={Boolean(status.lastSyncedAt)} shopDomain={status.shopDomain} storeKey={storeKey}/>
    <UtmifyIntegration csrfToken={csrfToken} storeKey={storeKey}/>
    <MetaIntegration csrfToken={csrfToken} storeKey={storeKey}/>
    <section className="integration-layout"><div className="card shopify-card"><div className="integration-heading"><span className="shopify-brand"><ShoppingBag size={25}/></span><div><h2>Shopify Admin</h2><p>Produtos, variantes, imagens e coleções serão importados para esta loja SOLID.</p></div></div>
      {status.loading ? <div className="integration-loading"><LoaderCircle className="spin"/> Verificando conexão...</div> : status.connected ? <div className="connected-content"><div className="connected-panel"><div><span>Loja conectada</span><strong>{status.shopDomain}</strong><small>Última sincronização: {formatDate(status.lastSyncedAt)}</small></div><button className="secondary danger-outline" disabled={busy || syncing} onClick={disconnect}>{busy ? <LoaderCircle className="spin" size={17}/> : <Unplug size={17}/>} Desconectar</button></div><div className="catalog-sync"><div><h3>Catálogo Shopify</h3><p>Atualiza dados de origem sem substituir os textos personalizados no checkout.</p></div><button className="primary sync-button" disabled={syncing || busy} onClick={synchronize}>{syncing ? <LoaderCircle className="spin" size={17}/> : <RefreshCw size={17}/>} {syncing ? 'Sincronizando...' : 'Sincronizar catálogo'}</button></div>{result && <div className="sync-result"><span><ShoppingBag size={16}/><strong>{result.products}</strong> produtos</span><span><Layers3 size={16}/><strong>{result.collections}</strong> coleções</span><span><Images size={16}/><strong>{result.images}</strong> imagens</span><span><RefreshCw size={16}/><strong>{result.variants}</strong> variantes</span></div>}</div> : <form onSubmit={connect}><label htmlFor="shopify-shop">Domínio MyShopify</label><div className="shop-domain-field"><input id="shopify-shop" value={shop} onChange={event => setShop(event.target.value)} placeholder="minha-loja" autoComplete="off" required/><span>.myshopify.com</span></div><small>Use o domínio original da Shopify, sem https:// ou www.</small><button className="primary connect-button" disabled={busy || !status.configured}>{busy ? <LoaderCircle className="spin" size={17}/> : <ExternalLink size={17}/>} {busy ? 'Redirecionando...' : status.reconnectRequired ? 'Reconectar Shopify' : 'Conectar com Shopify'}</button>{!status.configured && <p className="configuration-warning">A integração precisa ser configurada no servidor antes da conexão.</p>}{status.reconnectRequired && <p className="reconnect-preserved">O catálogo importado permanecerá salvo durante a reconexão.</p>}</form>}
    </div><aside className="card integration-security"><span><ShieldCheck size={23}/></span><h2>Conexão protegida</h2><p>Você autoriza o acesso diretamente na Shopify. A SOLID nunca solicita sua senha.</p><ul><li>Acesso somente de leitura ao catálogo</li><li>Token criptografado no banco</li><li>Dados separados por loja</li><li>Personalizações preservadas</li></ul></aside></section></main>;
}
