import React, { useEffect, useState } from 'react';
import { Activity, CheckCircle2, KeyRound, LoaderCircle, ShieldCheck, Unplug } from 'lucide-react';
import { disconnectUtmify, getUtmifyStatus, saveUtmify } from './api';

export default function UtmifyIntegration({ csrfToken, storeKey }) {
  const [status, setStatus] = useState({ loading: true, connected: false }); const [token, setToken] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = () => getUtmifyStatus().then(value => setStatus({ ...value, loading: false })).catch(error => { setStatus({ loading: false, connected: false }); setMessage(error.message); });
  useEffect(() => { setStatus({ loading: true, connected: false }); setToken(''); setMessage(''); void load(); }, [storeKey]);
  const connect = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const value = await saveUtmify(token, csrfToken); setStatus({ ...value, loading: false }); setToken(''); setMessage('UTMify conectada e validada com sucesso.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const disconnect = async () => { if (!window.confirm('Desconectar a UTMify desta loja?')) return; setBusy(true); try { await disconnectUtmify(csrfToken); setStatus({ loading: false, connected: false }); setMessage('UTMify desconectada.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <section className="utmify-section"><div className="utmify-title"><div><p className="eyebrow">RASTREAMENTO DE VENDAS</p><h2>UTMify</h2><p>Envie pedidos Pix pendentes e pagos automaticamente para sua operação de tráfego.</p></div>{status.connected && <span className="connection-pill connected"><CheckCircle2 size={15}/> Ativo</span>}</div>{message && <div className="integration-alert" role="status">{message}</div>}<div className="integration-layout"><div className="card shopify-card"><div className="integration-heading"><span className="utmify-brand"><Activity size={25}/></span><div><h2>UTMify Orders</h2><p>A credencial pertence à loja selecionada e nunca é exposta no checkout.</p></div></div>{status.loading ? <div className="integration-loading"><LoaderCircle className="spin"/> Verificando integração...</div> : status.connected ? <div className="connected-panel"><div><span>Status da integração</span><strong>Rastreamento automático ativado</strong><small>Pix gerado: aguardando pagamento · Pix confirmado: pago</small></div><button className="secondary danger-outline" disabled={busy} onClick={disconnect}><Unplug size={17}/> Desconectar</button></div> : <form onSubmit={connect}><label htmlFor="utmify-token">Token da API</label><div className="utmify-token-field"><KeyRound size={18}/><input id="utmify-token" type="password" value={token} onChange={event => setToken(event.target.value)} placeholder="Cole a credencial gerada na UTMify" autoComplete="off" required/></div><small>Na UTMify, acesse Integrações → Webhooks → Credenciais de API.</small><button className="primary connect-button" disabled={busy || token.trim().length < 10}>{busy ? <LoaderCircle className="spin" size={17}/> : <Activity size={17}/>} {busy ? 'Validando...' : 'Conectar UTMify'}</button></form>}</div><aside className="card integration-security"><span><ShieldCheck size={23}/></span><h2>Dados protegidos</h2><p>O token é criptografado e os eventos são enviados somente pelo servidor.</p><ul><li>Credencial separada por loja</li><li>Pagamento não depende da UTMify</li><li>Pedidos usam um identificador estável</li><li>Falhas não interrompem o checkout</li></ul></aside></div></section>;
}
