import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AppEnvironment } from '@solid/config';
import type { PrismaClient } from '@solid/database';
import type { AuthRepository } from './auth-repository.js';
import { decryptSecret, encryptSecret } from './shopify-crypto.js';

export const webhookEvents = ['order.created','order.paid','order.cancelled','order.refunded','payment.failed'] as const;
export type StoreWebhookDispatcher=(storeId:string,event:typeof webhookEvents[number],data:Record<string,unknown>)=>Promise<void>;
const sha256=(value:string)=>createHash('sha256').update(value).digest('hex');
const safeEqual=(left:string,right:string)=>timingSafeEqual(Buffer.from(sha256(left),'hex'),Buffer.from(sha256(right),'hex'));
const errorBody=(request:FastifyRequest,code:string,message:string)=>({error:{code,message,requestId:request.id}});
const privateAddress=(address:string)=>address==='::1'||address.startsWith('fc')||address.startsWith('fd')||address.startsWith('fe80')||/^127\.|^10\.|^169\.254\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(address);
async function safeWebhookUrl(value:unknown){ if(typeof value!=='string'||value.length>2048)throw new Error('Informe uma URL válida.'); let url:URL;try{url=new URL(value);}catch{throw new Error('Informe uma URL válida.');} if(url.protocol!=='https:'||url.username||url.password||url.port)throw new Error('Use uma URL HTTPS pública, sem credenciais ou porta personalizada.'); const addresses=isIP(url.hostname)?[{address:url.hostname}]:await lookup(url.hostname,{all:true}); if(!addresses.length||addresses.some(item=>privateAddress(item.address)))throw new Error('A URL deve apontar para um servidor público.'); return url.toString(); }
function validEvents(value:unknown):string[]{ if(!Array.isArray(value)||!value.length||value.length>webhookEvents.length)throw new Error('Selecione pelo menos um evento.'); const events=[...new Set(value.filter((item):item is string=>typeof item==='string'))]; if(events.some(event=>!webhookEvents.includes(event as typeof webhookEvents[number])))throw new Error('Evento inválido.'); return events; }

export function createStoreWebhookDispatcher(environment:AppEnvironment,database:PrismaClient):StoreWebhookDispatcher{return async(storeId,event,data)=>{if(!environment.APP_ENCRYPTION_KEY)return;const endpoints=await database.webhookEndpoint.findMany({where:{storeId,active:true,events:{has:event}}});await Promise.allSettled(endpoints.map(async endpoint=>{const body=JSON.stringify({id:`evt_${Date.now()}_${randomBytes(6).toString('hex')}`,event,createdAt:new Date().toISOString(),test:false,data});const timestamp=Math.floor(Date.now()/1000).toString(),secret=decryptSecret(endpoint.secretEncrypted,environment.APP_ENCRYPTION_KEY!);const started=Date.now();try{await safeWebhookUrl(endpoint.url);const response=await fetch(endpoint.url,{method:'POST',redirect:'error',signal:AbortSignal.timeout(10_000),headers:{'content-type':'application/json','user-agent':'SOLID-Webhooks/1.0','x-solid-event':event,'x-solid-timestamp':timestamp,'x-solid-signature':`sha256=${createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex')}`},body});await database.webhookDelivery.create({data:{storeId,webhookEndpointId:endpoint.id,event,success:response.ok,statusCode:response.status,durationMs:Date.now()-started,error:response.ok?null:`HTTP ${response.status}`}});}catch(error){await database.webhookDelivery.create({data:{storeId,webhookEndpointId:endpoint.id,event,success:false,durationMs:Date.now()-started,error:(error instanceof Error?error.message:'Falha de conexão').slice(0,500)}});}}));};}

export function registerWebhookRoutes(app:FastifyInstance,environment:AppEnvironment,auth:AuthRepository,database:PrismaClient):void{
  const sessionCookie=environment.NODE_ENV==='production'?'__Host-solid_session':'solid_session'; const csrfCookie=environment.NODE_ENV==='production'?'__Host-solid_csrf':'solid_csrf';
  const context=async(request:FastifyRequest,mutation=false)=>{const token=request.cookies[sessionCookie];const current=token?await auth.findActiveSession(sha256(token),new Date()):null;if(!current)return null;if(mutation){const origin=request.headers.origin,cookie=request.cookies[csrfCookie],header=request.headers['x-csrf-token'];if(typeof origin!=='string'||!environment.CORS_ORIGINS.includes(origin)||!cookie||typeof header!=='string'||!safeEqual(cookie,header)||!safeEqual(sha256(header),current.csrfTokenHash))return null;}const active=await database.session.findFirst({where:{id:current.sessionId,userId:current.userId,revokedAt:null},select:{activeStoreId:true}});if(!active?.activeStoreId)return null;const member=await database.storeMember.findUnique({where:{storeId_userId:{storeId:active.activeStoreId,userId:current.userId}},select:{role:true}});return member?{storeId:active.activeStoreId,writable:['OWNER','ADMIN'].includes(member.role)}:null;};
  app.get('/store-webhooks',async(request,reply)=>{const ctx=await context(request);if(!ctx)return reply.code(401).send(errorBody(request,'UNAUTHENTICATED','Autenticação necessária.'));const items=await database.webhookEndpoint.findMany({where:{storeId:ctx.storeId},orderBy:{createdAt:'desc'},select:{publicId:true,name:true,description:true,url:true,active:true,events:true,createdAt:true,updatedAt:true,_count:{select:{deliveries:true}},deliveries:{orderBy:{createdAt:'desc'},take:1,select:{success:true,statusCode:true,createdAt:true,error:true}}}});return reply.header('cache-control','private, no-store').send({items,writable:ctx.writable,events:webhookEvents});});
  app.post<{Body:{name?:unknown;description?:unknown;url?:unknown;secret?:unknown;active?:unknown;events?:unknown}}>('/store-webhooks',async(request,reply)=>{const ctx=await context(request,true);if(!ctx?.writable)return reply.code(403).send(errorBody(request,'FORBIDDEN','Acesso negado.'));if(!environment.APP_ENCRYPTION_KEY)return reply.code(503).send(errorBody(request,'SERVICE_UNAVAILABLE','Criptografia indisponível.'));try{const name=typeof request.body?.name==='string'?request.body.name.trim():'';if(name.length<2||name.length>120)throw new Error('Informe um nome entre 2 e 120 caracteres.');const description=typeof request.body.description==='string'?request.body.description.trim().slice(0,240):null;const url=await safeWebhookUrl(request.body.url);const events=validEvents(request.body.events);const secret=typeof request.body.secret==='string'&&request.body.secret.trim().length>=16?request.body.secret.trim():randomBytes(32).toString('hex');const item=await database.webhookEndpoint.create({data:{storeId:ctx.storeId,name,description:description||null,url,active:request.body.active!==false,events,secretEncrypted:encryptSecret(secret,environment.APP_ENCRYPTION_KEY)},select:{publicId:true,name:true,description:true,url:true,active:true,events:true}});return reply.code(201).send({item,secret});}catch(error){return reply.code(400).send(errorBody(request,'VALIDATION_ERROR',error instanceof Error?error.message:'Dados inválidos.'));}});
  app.patch<{Params:{id:string};Body:{name?:unknown;description?:unknown;url?:unknown;active?:unknown;events?:unknown}}>('/store-webhooks/:id',async(request,reply)=>{const ctx=await context(request,true);if(!ctx?.writable)return reply.code(403).send(errorBody(request,'FORBIDDEN','Acesso negado.'));const existing=await database.webhookEndpoint.findFirst({where:{publicId:request.params.id,storeId:ctx.storeId}});if(!existing)return reply.code(404).send(errorBody(request,'NOT_FOUND','Webhook não encontrado.'));try{const data:{name?:string;description?:string|null;url?:string;active?:boolean;events?:string[]}={};if(request.body.name!==undefined){const name=typeof request.body.name==='string'?request.body.name.trim():'';if(name.length<2||name.length>120)throw new Error('Nome inválido.');data.name=name;}if(request.body.description!==undefined)data.description=typeof request.body.description==='string'?request.body.description.trim().slice(0,240)||null:null;if(request.body.url!==undefined)data.url=await safeWebhookUrl(request.body.url);if(typeof request.body.active==='boolean')data.active=request.body.active;if(request.body.events!==undefined)data.events=validEvents(request.body.events);const item=await database.webhookEndpoint.update({where:{id:existing.id},data,select:{publicId:true,name:true,description:true,url:true,active:true,events:true}});return reply.send({item});}catch(error){return reply.code(400).send(errorBody(request,'VALIDATION_ERROR',error instanceof Error?error.message:'Dados inválidos.'));}});
  app.delete<{Params:{id:string}}>('/store-webhooks/:id',async(request,reply)=>{const ctx=await context(request,true);if(!ctx?.writable)return reply.code(403).send(errorBody(request,'FORBIDDEN','Acesso negado.'));const result=await database.webhookEndpoint.deleteMany({where:{publicId:request.params.id,storeId:ctx.storeId}});return result.count?reply.code(204).send():reply.code(404).send(errorBody(request,'NOT_FOUND','Webhook não encontrado.'));});
  app.post<{Params:{id:string};Body:{event?:unknown}}>('/store-webhooks/:id/test',async(request,reply)=>{const ctx=await context(request,true);if(!ctx?.writable)return reply.code(403).send(errorBody(request,'FORBIDDEN','Acesso negado.'));if(!environment.APP_ENCRYPTION_KEY)return reply.code(503).send(errorBody(request,'SERVICE_UNAVAILABLE','Criptografia indisponível.'));const endpoint=await database.webhookEndpoint.findFirst({where:{publicId:request.params.id,storeId:ctx.storeId}});if(!endpoint)return reply.code(404).send(errorBody(request,'NOT_FOUND','Webhook não encontrado.'));const event=typeof request.body?.event==='string'?request.body.event:'order.created';if(!webhookEvents.includes(event as typeof webhookEvents[number]))return reply.code(400).send(errorBody(request,'VALIDATION_ERROR','Evento inválido.'));try{await safeWebhookUrl(endpoint.url);const body=JSON.stringify({id:`evt_test_${Date.now()}`,event,createdAt:new Date().toISOString(),test:true,data:{order:{id:'SLD-EXEMPLO',status:'PENDING',totalCents:9990,currency:'BRL'}}});const timestamp=Math.floor(Date.now()/1000).toString(),secret=decryptSecret(endpoint.secretEncrypted,environment.APP_ENCRYPTION_KEY);const started=Date.now();let response:Response;try{response=await fetch(endpoint.url,{method:'POST',redirect:'error',signal:AbortSignal.timeout(10_000),headers:{'content-type':'application/json','user-agent':'SOLID-Webhooks/1.0','x-solid-event':event,'x-solid-timestamp':timestamp,'x-solid-signature':`sha256=${createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex')}`},body});}catch(error){await database.webhookDelivery.create({data:{storeId:ctx.storeId,webhookEndpointId:endpoint.id,event,success:false,durationMs:Date.now()-started,error:(error instanceof Error?error.message:'Falha de conexão').slice(0,500)}});throw error;}await database.webhookDelivery.create({data:{storeId:ctx.storeId,webhookEndpointId:endpoint.id,event,success:response.ok,statusCode:response.status,durationMs:Date.now()-started,error:response.ok?null:`HTTP ${response.status}`}});return reply.send({success:response.ok,statusCode:response.status,durationMs:Date.now()-started});}catch(error){return reply.code(502).send(errorBody(request,'DELIVERY_FAILED',error instanceof Error?error.message:'Falha no envio.'));}});
}
